### ISSUE TITLE
IPTV機能について

### ISSUE THREAD

**Issue by trimethia** [Chinachu/Mirakurun#100]
先日導入されたIPTV機能ありがとうございます。IPTV機能だけのためにEPGStationを使っていたので、Mirakurunだけで完結できるようになり大変助かります。そこで質問ですが、Transcodingを目的に、IPTVで提供されるStreamに対して任意のffmpegのコマンドを適用するような機能が予定されていますでしょうか？

よろしくお願いいたします。

**Comment by kanreisa** [comment]
こんにちは
Mirakurun 自体は LAN 専用サーバーであるため、そのような機能は予定しておりません。
Plex や Emby 等の完成度の高いメディアサーバーを経由していただくのが手っ取り早いかなと思います。
どうぞよろしくお願いいたします。
（回答後 Close いたしますが、関連するトピックは続けていただいて構いません！）
