### ISSUE TITLE
websocketのSSL対応

### ISSUE THREAD

**Issue by 5ym** [Chinachu/Mirakurun#102]
### Request (要望の内容)

3.9.0-beta.0においてwebcoketのクライアントを更新されているようですが，一律でws://をもちいているため，httpsでweb UIにアクセスした際に正常にどうさしません
必須の対応ではないと思いますが，なにとぞ確認よろしくお願いいたします。

https://github.com/Chinachu/Mirakurun/blob/9bade6e46df17ab41f629f8f032add98eef07afa/src/ui/index.tsx#L100

**Comment by kanreisa** [comment]
こんにちは、Request をありがとうございます。

Mirakurun は SSL 接続を一切考慮して開発しておらず、
そもそも SSL サーバー機能は実装されていません。
ここだけ対応しても他で不具合が出る可能性があります。
一部分だけ中途半端に SSL 接続に対応するとプロジェクトとしてのメンテナンスコストが大きく跳ね上がります。（現在当研究会は慢性的にリソースが不足しています）
なぜ SSL 経由でのアクセスが必要なのか理由を書いていただければ検討材料とさせていただきます。

どうぞよろしくお願いいたします。

**Comment by 5ym** [comment]
内向きにもHSTSドメインを使用しているため完全にweb UIが利用できないです
サーバで直接確認すればいい話なので必須ではないです
