### ISSUE TITLE
同じ番組が複数録画される [BUG]

### ISSUE THREAD

**Issue by ttytb** [Chinachu/Mirakurun#103]
- `uname -srvmo`: `Linux 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 GNU/Linux`
- `cat /etc/issue`: `Ubuntu 20.04.3 LTS \n \l`
- `cat /proc/cpuinfo | grep name -m 1`: `model name      : AMD Athlon(tm) 5350 APU with Radeon(tm) R3`
- Version of Mirakurun: `3.9.0-beta.1`
- Version of Node: `v16.7.0`
- Version of NPM: `7.21.0`

### Issue (不具合の内容)

3.9.0-beta.0 にアップデートして以降、EPGStation(v2.6.10)で同じ番組がサブチャンネル数分、複数録画されます。
3.9.0-beta.1 でも変化ありませんでした。
EPGStationでIssueを建てましたが、Mirakurun側ではないかとのことでしたので、こちらに建てました。

### Expected (期待される動作)

1個だけ録画される。

**Comment by kanreisa** [comment]
こんにちは、フィードバックありがとうございます。
察するに意図した動作です。
EIT[p/f] を取り込むことにしたため、今まで name 等の取得できていなかった情報が取得できるようになったためです。
ひとまず重複しないようにするには、予約ルールでサービスIDを指定すると良いと思います。
根本的には shared になっているイベントグループの予約が重複しないように、録画ソフト側で対応が必要です。
どうぞよろしくお願いいたします。

**Comment by kanreisa** [comment]
ref: https://github.com/l3tnun/EPGStation/issues/525

**Comment by ttytb** [comment]
意図した動きということで、承知しました。
回答ありがとうございました。
