### ISSUE TITLE
Web UIで外部(インターネット)からフォントを読み込んでしまっている

### ISSUE THREAD

**Issue by helmetplumeggbanana** [Chinachu/Mirakurun#105]
Web UI(既定ではlocalhost:40772で動くページ)で、外部からフォントを読み込んでいます。
具体的には、spoprod-a.akamaihd.netから4つのwoffファイル読み込んでいます。
Mirakurunはローカルネットワークで動かし、インターネットには公開しないことが前提のプログラムかと存じます。そのため、インターネットと接続されていないローカルネットワークのクライアントからWeb UIを開くことも容易に考えられます。

このような事情を考慮すると、外部からフォントを読み込むのは望ましくないと考えます。主観になりますが、なんとなく気持ち悪いです。

**Comment by kanreisa** [comment]
ご報告ありがとうございます。
ご指摘の件は意図した挙動です。
インターネットに繋がっていない状態でも一応表示できることを確認済みです。
この件は修正する予定がありませんが、修正は大歓迎ですので、PR 頂ければレビューいたします。
どうぞよろしくお願いいたします。

**Comment by kanreisa** [comment]
本件に関連して Web UI を無効化するオプションを追加しました
