### ISSUE TITLE
Web UIで外部(インターネット)から画像を読み込んでしまっている 

### ISSUE THREAD

**Issue by helmetplumeggbanana** [Chinachu/Mirakurun#106]
#105 と同様の問題です。
opencollective.comおよびimages.opencollective.comから画像を読み込んでいます。
貢献者の名前を載せるのは理解できますが、アイコンをプログラムに含める必要があるとは思えません。
せめて外部から読み込まず、内部でアイコンを保持すべきです。

images〜に至っては1pxのトラッキング用と思わしき画像まで含まれています。プライバシーの観点から好ましくなく、スパイウェアまがいの挙動なので修正してはどうでしょうか。

**Comment by kanreisa** [comment]
ご報告ありがとうございます。
内容については意図した挙動ですが、ご指摘は理解しております。
当該の表示を行う際に警告を表示して同意した場合に表示するようにしたいと思います。
表示しない限りリクエストは行われませんので、回避策としては当該のタブをクリックしないでください。
どうぞよろしくお願いいたします。

**Comment by kanreisa** [comment]
`@3.9.0-beta.5` で対応しました
