### ISSUE TITLE
放送局が直前に停波していると録画のスクランブルが解除されない

### ISSUE THREAD

**Issue by tomo0611** [Chinachu/Mirakurun#107]
### Environment (再現している環境)

- OS : `Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-81-generic x86_64)`
- Version of Mirakurun: `3.9.0-beta.3`
- Version of Node: `v16.8.0`
- Version of NPM: `v7.21.0`

### Issue (不具合の内容)
各放送局のオープニングを録画するとBS朝日やBS11イレブンでスクランブルが解除されなかった。

![image](https://user-images.githubusercontent.com/31959526/131415272-43f8ddad-84b8-4917-bc53-760bda2bb88c.png)

一方で、関西テレビやサンテレビ、KBS京都などのオープニングはなんの問題もなくスクランブルを解除されていた。

各放送局のオープニングの直前の放送を調べると問題の起きなかった放送局では直前に無名の番組や試験電波(OP前)などといった番組が入っていた。これにより、停波終了直後の番組のみで起こる問題であると考えられる。

また、FIGAやEDCBとEPGSでは問題なく録画されており再生できたとの報告があった。

さらに、録画後にB25を利用してスクランブルを解除すると問題なく視聴できた。

![image](https://user-images.githubusercontent.com/31959526/131415347-f34540d0-c8a7-47e6-a35d-3f66210b2980.png)

(removed image)

(removed image)

...

### Expected (期待される動作)

直前の停波の有無に関わらず、スクランブルを解除する。

...

**Comment by tomo0611** [comment]
[追加]

Mirakurunのログ見てもなにもなく、録画コマンドが怪しいと考えてみたところ、

https://github.com/stz2012/recpt1/blob/master/recpt1/recpt1.c#L328
![image](https://user-images.githubusercontent.com/31959526/131417277-949ec17d-3496-4ead-85f6-5c6859c5856e.png)

バッファーを取る→停波してるので空→デコードエラーでB25が無効化→スクランブルされた生データが書き込まれる、って感じになってるんですかね、、？

似たようなissueも発見しました
https://github.com/stz2012/recpt1/issues/9

**Comment by kanreisa** [comment]
（大人の事情で一部画像への参照を削除しました）

Issue を報告される際はテンプレートやガイドラインに書いてある内容をよくお読みになり、
他の人が再現できるように、できる限りの環境情報を記載をお願いしています。

録画コマンドやスクランブルの解除については当プロジェクトでは取り扱っていませんので、クローズいたします。
