### ISSUE TITLE
地上波の番組をChinachuで録画中に、同じ物理チャンネルの別サービスが /api/channels/GR/{channel}/stream で取得できない [BUG]

### ISSUE THREAD

**Issue by taikoyaP** [Chinachu/Mirakurun#110]
- `uname -srvmo`: `Linux 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux`
- `cat /etc/issue`: `Debian GNU/Linux 11`
- `cat /proc/cpuinfo | grep name -m 1`: `Intel(R) Celeron(R) CPU G3930 @ 2.90GHz`
- Version of Mirakurun: `3.9.0 beta9`
- Version of Node: `v16.8.0`
- Version of NPM: `7.24.0`

### Issue (不具合の内容)

同じ物理チャンネルで複数のサービスが提供されているチャンネルで、Chinachuを使って一方のサービス(例: TOKYO MX 1)の番組を録画しているときに、TvTest + BonDriver_Mirakurunを使ってもう一方のサービス(例: TOKYO MX 2)を視聴しようとすると、Chinachuを使って録画しているサービスのみが視聴でき、もう一方のサービスが視聴できません。

問題が発生しているときの、TvTestの「ストリームの情報」の内容が以下になります。
![スクリーンショット 2021-09-23 072723](https://user-images.githubusercontent.com/2113819/134431568-0d9d85eb-e3c6-4c79-8a4f-1e3b29957e8f.jpg)

問題が発生していないとき(Chinachuで録画を行っておらず、TOKYO MX 2が視聴できるとき)の同情報が以下になります。
![スクリーンショット 2021-09-23 072803](https://user-images.githubusercontent.com/2113819/134431704-12b92fa5-75fd-4882-a0ac-bc7d81cad4e8.jpg)

### Expected (期待される動作)

録画をしている場合でも、同じ物理チャンネルの別サービスが視聴できること。

**Comment by taikoyaP** [comment]
書きかけで送ってしまいました。書き終わりましたのでReopenしました。

**Comment by kanreisa** [comment]
これはこれは、ありがとうございます
`3.9.0-beta.10` で修正しましたので、ご確認ください

**Comment by taikoyaP** [comment]
ありがとうございます。直っていることを確認しました。
これで22時のアニメを録りながら裏のニュースを見られます。
