### ISSUE TITLE
PX-MLT8PEで6ch全録を実施するとメモリ使用量が4.7GBになる。

### ISSUE THREAD

**Issue by simplelife0530** [Chinachu/Mirakurun#111]
### Environment (再現している環境)
- `cat /etc/issue`: Ubuntu 20.04.3 LTS
- `cat /proc/cpuinfo | grep name -m 1`: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
- Version of Mirakurun: `3.5.0`
- Version of Docker: 20.10.7

### Issue (不具合の内容)
PX-Q3PE4のチューナーカードを使い、EPGStation v2で6ch全録を行った場合、
（地上波４，BS２）
Mirakurunのメモリ使用量　180MB(6ch予約）
エンコード処理7倍速で1週間問題なく動作。

不具合の例
PX-MLT8PEのチューナーカードを使い、EPGStation v2で6ch全録を行った場合、
（地上波６）
Mirakurunのメモリ使用量　280MB(6ch予約）
午前1時　メモリ使用量　4.7GB
iowait 45%となり、エンコード処理1倍速まで低下。SWAP 2GB(100%)
予約を全部取り消すと、メモリ使用量3.1GB
エンコード処理7倍速に戻る。

### Expected (期待される動作)

できれば、PX-Q3PE4のチューナーカードと同じ速度でエンコードしてほしいが、
Mirakurunのメモリ使用量が予想以上に大きくなるため、swapが発生し、エンコードが低速化。
メモリ8GBを16GBに増設という方法もあるが、できればメモリ消費量を抑えたいところです。

PLEX非公式ドライバの問題か、Mirakurunの問題か、まだわかりません。
何か原因を調べる方法があれば教えてください。

...

**Comment by kanreisa** [comment]
- まずは Mirakurun のバージョンを上げて試してみてください。割と多くのバグが修正されています。
- 次に docker-compose でメモリ使用量を制限することができますので、そちらも試してみてください。
  - （制限しすぎると動作しない場合があります）
- ffmpeg をお使いであればスレッド数を減らしてみるのも手かと思います。

**Comment by simplelife0530** [comment]
> Discord で確認してください。

Discordにアカウント作りました。今後は、そちらで。
