### ISSUE TITLE
"docker-compose run --rm -e SETUP=true mirakurun"で「/usr/local/mirakurun/run/が存在しない」とのエラー [BUG]

### ISSUE THREAD

**Issue by rasumus** [Chinachu/Mirakurun#112]
### Environment (再現している環境)
- `uname -srvmo`: `Linux 5.15.2-2-MANJARO #1 SMP PREEMPT Sat Nov 13 19:25:38 UTC 2021 x86_64 GNU/Linux`
- `cat /etc/issue`: `Manjaro Linux`
- `cat /proc/cpuinfo | grep name -m 1`: `AMD A10-7800 Radeon R7, 12 Compute Cores 4C+8G`
- Version of Mirakurun: 
     $ cat docker-compose.yml 
     version: "3.7"
     networks:
       default:
         name: mirakurun
- Version of Docker: `20.10.10`
- Version of Node: v16.11.1
- Version of NPM: 8.1.3
- Client OS: Manjaro Linux
- Browser: Firefox 94.0.2

### Issue (不具合の内容)
Docker版Mirakurunのインストールにおいて、"docker-compose run --rm -e SETUP=true mirakurun"を実行すると「/usr/local/mirakurun/run/が存在しない」とのエラーとなります。
以下の状況です。
```
$ mkdir ~/mirakurun/
$ cd ~/mirakurun/
$ wget https://raw.githubusercontent.com/Chinachu/Mirakurun/master/docker/docker-compose.yml
--2021-11-20 14:33:58--  https://raw.githubusercontent.com/Chinachu/Mirakurun/master/docker/docker-compose.yml
SSL_INIT
CA証明書 '/etc/ssl/certs/ca-certificates.crt' をロードしました
raw.githubusercontent.com (raw.githubusercontent.com) をDNSに問いあわせています... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 200 OK
長さ: 803 [text/plain]
`docker-compose.yml' に保存中

docker-compose.yml  100%[===================>]     803  --.-KB/s 時間 0s       

2021-11-20 14:33:59 (14.0 MB/s) - `docker-compose.yml' へ保存完了 [803/803]

$ docker-compose pull
[+] Running 1/1
 ⠿ mirakurun Pulled

$ docker-compose run --rm -e SETUP=true mirakurun
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /usr/local/mirakurun/run/

$ ls /usr/local/
bin  etc  games  include  lib  man  my	sbin  share  src
```

### Expected (期待される動作)
/usr/local/mirakurun/config/tuners.ymlが生成されること。

**Comment by kanreisa** [comment]
Docker の挙動変更でディレクトリが作成されなくなったようなので、
```
mkdir -p 存在していないパス
```
でディレクトリを作成してください。

追ってドキュメントなど更新します。

**Comment by rasumus** [comment]
ありがとうございます。
御指示の通りで解決しました。
