### ISSUE TITLE
TSDecoder unexpected dead [BUG]

### ISSUE THREAD

**Issue by AdamGoodApp** [Chinachu/Mirakurun#115]
- `uname -srvmo`: `Linux 5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 GNU/Linux`
- `cat /etc/issue`: `Ubuntu 21.04`
- `cat /proc/cpuinfo | grep name -m 1`: `Intel(R) Xeon(R) CPU E3-1220 v3 @ 3.10GHz`
- Version of Mirakurun: `3.8.0`
- Version of Docker: `20.10.8`
-  Docker image: `chinachu/mirakurun:latest`

### Issue (不具合の内容)

```
error: TSDecoder#0 unexpected dead
warn: TSDecoder#0 has been fallback into pass-through stream
```

### Expected (期待される動作)
チャンネルを選択してもローディングされず、上記のエラーが起きる

**Comment by kanreisa** [comment]
https://github.com/Chinachu/Mirakurun/blob/master/CONTRIBUTING.md
