### ISSUE TITLE
Running Mirakurun on non-root user

### ISSUE THREAD

**Issue by akihiro** [Chinachu/Mirakurun#13]
mirakurunの非rootユーザでの実行を許可してほしい。

下記の箇所でのLinux環境でのroot権限チェックを取り除いてほしい。あるいはroot権限チェックをパスするオプションを追加してほしい。
https://github.com/Chinachu/Mirakurun/blob/master/src/server.ts#L20

セキュリティの観点から非特権ユーザーでプロセスを動かしたいです。

debian jessie環境のearth_pt3 driverならdefaultで、pt3_drv driverでもudev ruleを記述することでvideo group権限のみでtunnerのdevice fileへのRWが可能です。

Docker環境では--deviceオプションを使用した場合uid1000のユーザならばdeviceやvolumeへのRWが可能です。

**Comment by kanreisa** [comment]
> セキュリティの観点から非特権ユーザーでプロセスを動かしたいです。
具体的に、どういった懸念があるのでしょうか？

> Docker環境では--deviceオプションを使用した場合uid1000のユーザならばdeviceやvolumeへのRWが可能です。
Docker ではダメなのでしょうか？

**Comment by akihiro** [comment]
> 具体的に、どういった懸念があるのでしょうか？

mirakurunは外部に公開することはまずないプロダクトですが、任意コード実行の脆弱性が見つかった場合の脆弱性緩和策として非rootユーザーで実行しておきたいです。
特権ユーザーで実行していた場合にファイルの書き換えなどの影響があります。

> Docker ではダメなのでしょうか？

Docker自体はホスト環境から隔離されたコンテナ環境を提供しますがコンテナ環境内部のroot権限は有したままです。任意コード実行が出来てしまった場合にコンテナ内部で暴れてたり出来てしまいます。

Dockerでもrootユーザーで動作させることは最小権限の原則などに基づいて[DockerでのNodeアプリ構築で学んだこと](http://postd.cc/lessons-building-node-app-docker/)などでも推奨されてません。
（rootでプロセスを動かすイメージもたくさんあるのは事実ですが）

[nodejsオフィシャルイメージのDockerfile](https://github.com/nodejs/docker-node/blob/ad54b39ef23e0c7e0df3ac4234c3ee77b58c3f5d/6.9/Dockerfile)でも派生イメージで実行ユーザーを非特権化するためのユーザーをデフォルトで用意してたりします。

**Comment by kanreisa** [comment]
nginx のように master process = root と worker process = 非root を分けるような仕組みは検討していますが、それでも一部 root 相当の権限は必要な仕様です。なんにせよ Mirakurun は相当の理由をもって権限を必要としていますので、公式で非 root をサポートすることは今後も予定していません。

**Comment by upsilon** [comment]
> なんにせよ Mirakurun は相当の理由をもって権限を必要としていますので

その「相当な理由」が明確でないために @akihiro さんは Issue を作成されたのだと思います。

upsilon@f0aab0fbddd1dd07b26cd8a52e3a202b398fc9ce のような修正を施して Mirakurun を使っている一利用者として、私は Mirakurun が特権ユーザーでの実行を **要求する必要はない** と考えています。（なので、相当な理由を以てこれを否定して欲しいのです）

特に Mirakurun 自身が Linux における推奨環境としている Debian は、既に書かれている通り DVB デバイスについてはデフォルトで、pt3_drv についても udev の設定を加えることで video グループに属するユーザーによる rw アクセスを許可できることはご存知の通りだと思います。その上で Mirakurun を実行するユーザーが video グループに所属していればチューナーへのアクセスについて特権は不要です。

プロセス管理に使用する pm2 はシステムに startup script を配置する際に root 権限でのファイルシステムへのアクセスを必要としますが、インストール時を除けば `pm2 startup` に適切な引数を指定することで非特権ユーザーでアプリケーションを起動することができることはドキュメントに記載されている通りです。

http://pm2.keymetrics.io/docs/usage/startup/#user-permissions

明らかに特権を必要とする renice での負値の指定や ionice コマンドの使用についても、Mirakurun を動作させる上で必須といえるものではありません。 
（個人的な考えとしては、nice 値や ionice はアプリケーションが安易に変更すべきではなくシステム管理者の裁量によって適切な値を指定する領域であると思います）

もちろん、これらの設定を適切に行おうとすればインストール手順がより複雑になることは避けられないでしょう。しかし、それを避けるために常に特権ユーザーを要求して解決しようという目的がもしあるのであれば、それは少々乱暴であると思います（違ったらごめんなさい）

**Comment by kanreisa** [comment]
そうですか。わざわざコメントありがとうございました。

特権を必要とするのは挙げられた項目のほかにもあります。
（今は使われていないだけで、目立っていません。）
今後もいくつか特権を必要とする機能を実装予定です。

セキュリティと利便性はトレードオフであり、
こちらの価値観でバランスを意識して仕様を決めています。

因みに Mirakurun / Chinachu Air が想定している環境はDTV/DVRアプライアンス+LANです。
汎用サーバーではありません。システム管理者が居るような環境は想定していません。

当然バランスの範囲内でセキュリティ信頼性の向上を図っていきますので、「非 root ユーザで動かす」という要望は本来の本質から外れた議論だと言わざるを得ません。

**Comment by kanreisa** [comment]
議論する気がないのであれば初めから横やりを入れないでいただけますか。

もちろん改変は自由ですが、全て自己責任でお願いいたします。

**Comment by upsilon** [comment]
せっかく返答を下さったのに長らく放置してしまい失礼しました。

> 因みに Mirakurun / Chinachu Air が想定している環境はDTV/DVRアプライアンス+LANです。
> 汎用サーバーではありません。システム管理者が居るような環境は想定していません。

少なくとも私が疑問に思っていた点については、この前提によって解消されたと考えております。
例えばエンドユーザーにシェルアクセスを提供せずフロントエンドには Chinachu を介したインタフェースのみ存在するという状況を考えれば Chinachu 自身が特権を行使することは尤もです。
「セキュリティと利便性はトレードオフ」という言葉には首を傾げますが、あるべき機能に適切な権限が与えられている状況を意味しているのであれば疑念を抱くまでもないと思います。

ところで、私に対する反応はともかく、この Issue は won't fix で閉じてしまって良かったのでしょうか？
エントリポイントから非特権ユーザーで動かすという点については否定されている通りですが、
ご自身で worker process について言及されているように Mirakurun の一部を切り出して非特権ユーザーで動かす余地があるとお考えであれば、現状の Mirakurun のように全てが root で動くことを是としている訳ではないのですよね？

**Comment by kanreisa** [comment]
> 「セキュリティと利便性はトレードオフ」という言葉には首を傾げますが

upsilon さんのセキュリティ意識の高さには脱帽しますが、下記のようなイメージ図を
どこかで見たことがあるのではないでしょうか。

![](https://yabumi.cc/159d84715772e0be10abfb4f.png)

ここセキュリティに関する講義をする場ではないので、説明は割愛しますね。

> あるべき機能に適切な権限が与えられている状況

もちろんそれは意識をしていますが、そういう意味で言ったのではありません。

> この Issue は won't fix で閉じてしまって良かったのでしょうか？
> 現状の Mirakurun のように全てが root で動くことを是としている訳ではないのですよね？

一度回答した通り、「非 root ユーザで動かす」というのは本質から外れた議論です。これを目標に開発していくということはありませんので、閉じさせていただきました。本人からの返答もありませんでしたので。

あと、次回からはもう少し簡潔に文章を書いて頂けると嬉しいです。

**Comment by upsilon** [comment]
そうですか。簡潔な回答ありがとうございました。
せっかく画像まで用意して下さったのにご講授頂けないのは惜しいですが、私としては先のやり取りでやっと納得の行った所ですので特にこれ以上申し上げることはございません。
差し出がましいことを書きましたが、望ましい議論でなければクローズして頂いて良いと思います。

**Comment by kanreisa** [comment]
誤った意図が伝わるのは不本意ですので、まとめときます 📝  

* Mirakurun は常に安定したパフォーマンスをユーザー（人に限らない）に提供するために特権を要しています。（今後、負荷状況に応じたプロセス制御や自動アップデータ対応などのアップデートも予定されています）
* 当然のことながら、特権を必要以上広範囲にわたって保持することは宜しくないことだと認識しています。この件に関しては、計算リソースやパフォーマンスへの影響を意識しつつ、適切な仕組みを検討しています。（現在進行形; 現状が適切だと言っているわけでは無いです）
* とはいえ、特権問題にフォーカスしてしまって他の対策が疎かになってしまってはいけませんし、行き過ぎた対策によって悪戯に利便性＝パフォーマンスに影響を与えてしまってもどうかと思います。また、プロジェクトのメンテナンス性も合理的に保っていかなければなりません。
* 従って、現実的な線のセキュリティ対策を講じる事が本質であって、rootかどうかが主題ではないと考えています。

適当に対応してしまい申し訳ございませんでした。
