### ISSUE TITLE
NHK総合のEPGが取得できません…

### ISSUE THREAD

**Issue by vorbiser** [Chinachu/Mirakurun#14]
Ubuntu 16.10(Desktop) に新規で Chinachu(γ) + Mirakurunをインストールし、テストしています。
recpt1やrivarun 単体でのテスト録画できているのですが、Chinachuの番組表に"NHK総合のみ"表示されません。
テスト機・メイン機 共に同様のことが起こっていますのでバグかなと思うのですが、どうでしょうか…？

mirakurun: 2.0.0-rc.13
OS: ubuntu 16.10 (Desktop、apt upgradeで最新の状態)
PC: x64、 Pentium N3700
api status:
{
  "version": "2.0.0-rc.13",
  "process": {
    "arch": "x64",
    "platform": "linux",
    "versions": {
      "http_parser": "2.7.0",
      "node": "7.4.0",
      "v8": "5.4.500.45",
      "uv": "1.10.1",
      "zlib": "1.2.8",
      "ares": "1.10.1-DEV",
      "modules": "51",
      "openssl": "1.0.2j",
      "icu": "58.2",
      "unicode": "9.0",
      "cldr": "30.0.3",
      "tz": "2016j"
    },
    "pid": 1350,
    "memoryUsage": {
      "rss": 80736256,
      "heapTotal": 32485376,
      "heapUsed": 25173336,
      "external": 2956740
    }
  },
  "epg": {
    "gatheringNetworks": [
      32391
    ],
    "storedEvents": 8101
  },
  "streamCount": {
    "tunerDevice": 1,
    "tsFilter": 1,
    "decoder": 0
  },
  "errorCount": {
    "uncaughtException": 0,
    "bufferOverflow": 0,
    "tunerDeviceRespawn": 0
  },
  "timerAccuracy": {
    "last": 0.87,
    "m1": {
      "avg": 447.6444833333333,
      "min": -692.991,
      "max": 4542.68
    },
    "m5": {
      "avg": -2761.8058866666665,
      "min": -999705.726,
      "max": 11449.298
    },
    "m15": {
      "avg": -920.6019622222223,
      "min": -999705.726,
      "max": 11449.298
    }
  }
}

**Comment by kanreisa** [comment]
@vorbiser 
`http:// *mirakurun:port* /api/services` の中に NHK 総合はありますか？

※ 本件とは無関係かと思いますが、 Node.js は偶数のバージョン（今は6）を使用してください。

**Comment by vorbiser** [comment]
再インストール、再設定を行ったところ 受信できるようになりました。
お騒がせしました。
