### ISSUE TITLE
【要望】MirakurunからBonDriver_Mirakurunへの送信をチャンネルごとではなくサービスごとに（ネットワーク帯域削減のため）

### ISSUE THREAD

**Issue by epgdatacapbon** [Chinachu/Mirakurun#16]
LinuxでMirakurunを導入し、Windows側でBonDriver_Mirakurunを使って視聴する場合、現在はワンセグも含めて、チャンネル内のすべてのサービスが送信されるようになっています。そのため、特にCSを視聴する場合にネットワークの帯域が圧迫されてしまいます。

そこで下のリンクのような要領で、
https://github.com/u-n-k-n-o-w-n/BonDriverProxy_Linux/blob/master/BonDriver_Splitter.conf
Mirakurunの方であらかじめ1チャンネル1サービスにスプリットしてから（この際に不要なPSI/SIを削除できるとなお良い）BonDriver_Mirakurunに送信できるようにしていただけると大変ありがたいです。

スプリットする/しない、削除するPSI/SIについてはBonDriver_Mirakurun.iniで指定できると良いと思いますが、Mirakurunのserver.ymlでもいいかもしれません。

ご考慮いただけましたら幸いです。

**Comment by kanreisa** [comment]
大変良いご要望だと思います。
お手数ですが下記リポジトリで再度Issueの作成をお願いいたします。
https://github.com/Chinachu/BonDriver_Mirakurun

**Comment by kanreisa** [comment]
大変失礼いたしました。よく見たところ既に作成されていましたので再openしておきました。
https://github.com/Chinachu/BonDriver_Mirakurun/issues/3

ちなみに Mirakurun 側のAPIでは既にサービス選択できるようになっています。
APIドキュメント: http:// _Mirakurun_ :40772/swagger-ui/?url=/api/docs#!/services/getServiceStream

**Comment by akimasa** [comment]
https://github.com/akimasa/Mirakurun/tree/delpids-dev
BonDriver_Mirakurunで不要なPIDを受信しないためにMirakurunに改変を加えてみました。
今のMirakurunのAPIでは指定されたPIDを送信させない機能はないですよね…？

改変を加えたMirakurunでは今のところ、指定されたサービスのストリームでしかPIDの削除が機能しない試作の状態になっています。
よろしければプルリクエストを送って、コードを見ていただき、修正点がありましたら指摘していただけたらと思うのですが、いかがいたしましょう。
あるいは、自分で書いた方が早いとお考えなら、その方が良いかもしれません。

**Comment by kanreisa** [comment]
nullパケットについては既に削除しているため、その他PIDを削除するメリットがいまいち分かっていません。
ちなみに、APIリクエストによって渡された文字列をそのままTSFilterで処理してはいけません。

**Comment by akimasa** [comment]
そうですね。
確かに自分も作ってみて、指定されたPID（PSI/SI）を削除するメリットがよくわかりませんでした。
ビットレートが目に見えて減るわけではないみたいですし、苦労して削除する割に合わない気がします。
node-aribts v1のcheck_drop.jsで眺めて見た限りでは、PSI/SIは全体の1%程度しか占めないみたいでした。
epgdatacapbonさんは、どうお考えなのか気になります。

//コードへのご指摘ありがとうございます。毎回へぼいコードで、すみません。

**Comment by epgdatacapbon** [comment]
akimasaさんコードありがとうございます。確かに費用対効果についてはあまり考えてませんでした。コードがかなり煩雑になる場合は別ですが、複数のtsを同時に転送することもあるので単純にネットワーク帯域が少しでも減らせればそれに越したことはないという考えでした。

**Comment by akimasa** [comment]
TSFilterの_processPacketで全てのパケットに対して削除するPIDかどうか調べて削除する処理を追加していました。これを追加すると、CPU使用率が上がる懸念があります。1%の削減のために、CPUを使うのはどうかなと思っていました。
しかし、よく考えたら元々提供するPIDの配列にあるかどうかチェックしているみたいのので、_providePidsからいらないPIDを消せば良かったみたいです。
これならおそらく機能を追加しても負荷が上がらないのでは無いかと思います。

TSFilterに文字列を直接渡していた件は直しておきました。
他にも問題点があるかと思いますが、指摘していただければ可能な限り直します。
それ以前に、指定されたPIDを削除する機能を採用するかどうかという問題がありますが…。

**Comment by kanreisa** [comment]
引き続き下記のスレで議論できます
https://github.com/Chinachu/BonDriver_Mirakurun/issues/3

EPG情報を削るオプションについては今後も検討してまいります。
