### ISSUE TITLE
BS/CSの局ロゴが取得できない

### ISSUE THREAD

**Issue by fugetutada** [Chinachu/Mirakurun#17]
Mirakurun -> BonDriver_Mirakurun -> TVTestでBS15_0をしばらく受信したのですが、Mirakurunが局ロゴを取得しませんでした。
TVTest側はロゴを全局取得できていたので、データは通過してきているようです。

**Comment by kanreisa** [comment]
地上波と方式が違うため、今のところは非対応ですが実装に向けて取り組んでいます。

**Comment by kanreisa** [comment]
52872e77b6555f0017b2115a580b07139efe1d77 で実装いたしました。
次回のバージョンでリリース予定です。
どうぞよろしくお願いいたします。

**Comment by trimethia** [comment]
@kanreisa 基本的質問で申し訳ないですが、BSロゴが反映されるまでの時間はどれぐらいでしょうか？
5時間前に3.8.0にアップデートしましたが、再スキャンしてもBSロゴが出てきていないようです。

**Comment by trimethia** [comment]
@kanreisa 詳細な情報をいただきありがとうございます。
30分程度を視聴するだけで、各チャンネルのBS/CSロゴが取得できることを確認できました。
