### ISSUE TITLE
アップデート時に pm2-root でエラーorz

### ISSUE THREAD

**Issue by nomiu26** [Chinachu/Mirakurun#18]
# npm install mirakurun@latest -g --unsafe --production               
                                                                                                                                            
> mirakurun@2.3.1 preinstall /usr/local/lib/node_modules/.staging/mirakurun-d2df8319
> node bin/preinstall.js

/usr/local/bin/mirakurun -> /usr/local/lib/node_modules/mirakurun/bin/cli.sh                                                                
/usr/local/bin/mirakurun-epgdump -> /usr/local/lib/node_modules/mirakurun/bin/epgdump.js
                                                                                                                                            
> mirakurun@2.3.1 postinstall /usr/local/lib/node_modules/mirakurun
> node bin/postinstall.js

[PM2] Init System found: systemd
Platform systemd
Template
[Unit]
Description=PM2 process manager
Documentation=https://pm2.keymetrics.io/
After=network.target

[Service]
Type=forking
User=root
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Environment=PATH=/usr/local/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Environment=PM2_HOME=/root/.pm2
PIDFile=/root/.pm2/pm2.pid

ExecStart=/usr/local/lib/node_modules/pm2/bin/pm2 resurrect
ExecReload=/usr/local/lib/node_modules/pm2/bin/pm2 reload all
ExecStop=/usr/local/lib/node_modules/pm2/bin/pm2 kill

[Install]
WantedBy=multi-user.target

Target path
/etc/systemd/system/pm2-root.service
Command list
[ 'chmod +x /etc/systemd/system/pm2-root.service',
  'systemctl enable pm2-root',
  'systemctl start pm2-root',
  'systemctl daemon-reload',
  'systemctl status pm2-root' ]
[PM2] Writing init configuration in /etc/systemd/system/pm2-root.service
[PM2] Making script booting at startup...
>>> Executing chmod +x /etc/systemd/system/pm2-root.service
[DONE] 
>>> Executing systemctl enable pm2-root
[DONE] 
>>> Executing systemctl start pm2-root
Job for pm2-root.service failed. See 'systemctl status pm2-root.service' and 'journalctl -xn' for details.
[ERROR] Exit code : 1
[PM2][ERROR] systemctl start pm2-root failed, see error above.
child_process.js:526
    throw err;
    ^

Error: Command failed: pm2 startup
    at checkExecSyncError (child_process.js:483:13)
    at Object.execSync (child_process.js:523:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/mirakurun/bin/postinstall.js:62:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
npm ERR! Linux 3.16.0-4-amd64                                                                                                               
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mirakurun@latest" "-g" "--unsafe" "--production"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! mirakurun@2.3.1 postinstall: `node bin/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mirakurun@2.3.1 postinstall script 'node bin/postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mirakurun package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mirakurun
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mirakurun
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

# systemctl start pm2-root                                                                                                     
Job for pm2-root.service failed. See 'systemctl status pm2-root.service' and 'journalctl -xn' for details.

# systemctl status pm2-root.service
● pm2-root.service - PM2 process manager
   Loaded: loaded (/etc/systemd/system/pm2-root.service; enabled)
   Active: failed (Result: timeout) since 金 2017-05-05 06:49:54 JST; 2min 23s ago
     Docs: https://pm2.keymetrics.io/
  Process: 580 ExecStart=/usr/local/lib/node_modules/pm2/bin/pm2 resurrect (code=killed, signal=TERM)

 5月 05 06:47:29 debian systemd[1]: Starting PM2 process manager...
 5月 05 06:47:40 debian pm2[580]: [PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
 5月 05 06:49:54 debian systemd[1]: pm2-root.service start operation timed out. Terminating.
 5月 05 06:49:54 debian systemd[1]: Failed to start PM2 process manager.
 5月 05 06:49:54 debian systemd[1]: Unit pm2-root.service entered failed state.

# journalctl -xn
-- Logs begin at 金 2017-05-05 06:47:22 JST, end at 金 2017-05-05 06:50:58 JST. --
 5月 05 06:50:58 debian su[1549]: pam_unix(su:session): session opened for user root by root(uid=0)
 5月 05 06:50:58 debian su[1549]: pam_unix(su:session): session closed for user root
 5月 05 06:50:58 debian sudo[1547]: pam_unix(sudo:session): session closed for user root
 5月 05 06:50:58 debian sudo[1552]: ^[[1;39mroot : TTY=pts/1 ; PWD=/usr/local/Chinachu ; USER=root ; COMMAND=/etc/init.d/chinachu-wui start
^[[0m
 5月 05 06:50:58 debian sudo[1552]: pam_unix(sudo:session): session opened for user root by root(uid=0)
 5月 05 06:50:58 debian su[1558]: Successful su for root by root
 5月 05 06:50:58 debian su[1558]: + /dev/pts/1 root:root
 5月 05 06:50:58 debian su[1558]: pam_unix(su:session): session opened for user root by root(uid=0)
 5月 05 06:50:58 debian su[1558]: pam_unix(su:session): session closed for user root
 5月 05 06:50:58 debian sudo[1552]: pam_unix(sudo:session): session closed for user root

色々と思い当たることをやってみたがダメぽいです。お力をお貸し下さい。

**Comment by kanreisa** [comment]
一旦 root で `pm2 unstartup` を実行してからやってみてもらえますか？

**Comment by nomiu26** [comment]
# pm2 unstartup
[PM2] Init System found: systemd
[PM2] Disabling and deleting old startup system
insserv: warning: current start runlevel(s) (empty) of script `pm2-init.sh' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `pm2-init.sh' overrides LSB defaults (0 1 6).

insserv: warning: current start runlevel(s) (empty) of script `pm2-init.sh' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `pm2-init.sh' overrides LSB defaults (0 1 6).

[PM2] Init file disabled.


# npm install mirakurun@latest -g --unsafe --production
                                                                                                                                            
> mirakurun@2.3.3 preinstall /usr/local/lib/node_modules/.staging/mirakurun-d2df8319
> node bin/preinstall.js

/usr/local/bin/mirakurun -> /usr/local/lib/node_modules/mirakurun/bin/cli.sh                                                                
/usr/local/bin/mirakurun-epgdump -> /usr/local/lib/node_modules/mirakurun/bin/epgdump.js
                                                                                                                                            
> mirakurun@2.3.3 postinstall /usr/local/lib/node_modules/mirakurun
> node bin/postinstall.js

[PM2] Init System found: systemd
Platform systemd
Template
[Unit]
Description=PM2 process manager
Documentation=https://pm2.keymetrics.io/
After=network.target

[Service]
Type=forking
User=root
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Environment=PATH=/usr/local/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Environment=PM2_HOME=/root/.pm2
PIDFile=/root/.pm2/pm2.pid

ExecStart=/usr/local/lib/node_modules/pm2/bin/pm2 resurrect
ExecReload=/usr/local/lib/node_modules/pm2/bin/pm2 reload all
ExecStop=/usr/local/lib/node_modules/pm2/bin/pm2 kill

[Install]
WantedBy=multi-user.target

Target path
/etc/systemd/system/pm2-root.service
Command list
[ 'chmod +x /etc/systemd/system/pm2-root.service',
  'systemctl enable pm2-root',
  'systemctl start pm2-root',
  'systemctl daemon-reload',
  'systemctl status pm2-root' ]
[PM2] Writing init configuration in /etc/systemd/system/pm2-root.service
[PM2] Making script booting at startup...
>>> Executing chmod +x /etc/systemd/system/pm2-root.service
[DONE] 
>>> Executing systemctl enable pm2-root
[DONE] 
>>> Executing systemctl start pm2-root
Job for pm2-root.service failed. See 'systemctl status pm2-root.service' and 'journalctl -xn' for details.
[ERROR] Exit code : 1
[PM2][ERROR] systemctl start pm2-root failed, see error above.
Caution: `pm2 startup` has failed. you can try fix yourself.
[PM2] Applying action restartProcessId on app [mirakurun-server](ids: 0)
[PM2] [mirakurun-server](0) ✓
┌──────────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name         │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ watching │
├──────────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ mirakurun-server │ 0  │ fork │ 11065 │ online │ 8       │ 0s     │ 0%  │ 19.6 MB   │ disabled │
└──────────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
[PM2] Saving current process list...
[PM2] Successfully saved in /root/.pm2/dump.pm2
/usr/local/lib
└─┬ mirakurun@2.3.3 
  ├─┬ aribts@1.3.3 
  │ ├── crc@3.4.4 
  │ └── iconv-lite@0.4.17 
  ├─┬ body-parser@1.17.1 
  │ ├── bytes@2.4.0 
  │ ├── content-type@1.0.2 
  │ ├─┬ debug@2.6.1 
  │ │ └── ms@0.7.2 
  │ ├── depd@1.1.0 
  │ ├─┬ http-errors@1.6.1 
  │ │ └── inherits@2.0.3 
  │ ├── iconv-lite@0.4.15 
  │ ├─┬ on-finished@2.3.0 
  │ │ └── ee-first@1.1.1 
  │ ├── qs@6.4.0 
  │ ├─┬ raw-body@2.2.0 
  │ │ ├── iconv-lite@0.4.15 
  │ │ └── unpipe@1.0.0 
  │ └─┬ type-is@1.6.15 
  │   ├── media-typer@0.3.0 
  │   └─┬ mime-types@2.1.15 
  │     └── mime-db@1.27.0 
  ├─┬ express@4.15.2 
  │ ├─┬ accepts@1.3.3 
  │ │ └── negotiator@0.6.1 
  │ ├── array-flatten@1.1.1 
  │ ├── content-disposition@0.5.2 
  │ ├── cookie@0.3.1 
  │ ├── cookie-signature@1.0.6 
  │ ├── encodeurl@1.0.1 
  │ ├── escape-html@1.0.3 
  │ ├── etag@1.8.0 
  │ ├─┬ finalhandler@1.0.2 
  │ │ └─┬ debug@2.6.4 
  │ │   └── ms@0.7.3 
  │ ├── fresh@0.5.0 
  │ ├── merge-descriptors@1.0.1 
  │ ├── methods@1.1.2 
  │ ├── parseurl@1.3.1 
  │ ├── path-to-regexp@0.1.7 
  │ ├─┬ proxy-addr@1.1.4 
  │ │ ├── forwarded@0.1.0 
  │ │ └── ipaddr.js@1.3.0 
  │ ├── range-parser@1.2.0 
  │ ├─┬ send@0.15.1 
  │ │ ├── destroy@1.0.4 
  │ │ └── mime@1.3.4 
  │ ├── serve-static@1.12.1 
  │ ├── setprototypeof@1.0.3 
  │ ├── statuses@1.3.1 
  │ ├── utils-merge@1.0.0 
  │ └── vary@1.1.1 
  ├─┬ express-openapi@0.33.0 
  │ ├── express-normalize-query-params-middleware@0.5.1 
  │ ├── express-openapi-coercion@0.5.0 
  │ ├── express-openapi-defaults@0.4.2 
  │ ├─┬ express-openapi-response-validation@0.3.0 
  │ │ └── jsonschema@1.1.1 
  │ ├─┬ express-openapi-security@0.2.0 
  │ │ └── async@1.5.2 
  │ ├─┬ express-openapi-validation@0.9.0 
  │ │ └── openapi-jsonschema-parameters@0.2.0 
  │ ├── fs-routes@1.0.3 
  │ ├─┬ glob@7.1.1 
  │ │ ├── fs.realpath@1.0.0 
  │ │ ├─┬ inflight@1.0.6 
  │ │ │ └── wrappy@1.0.2 
  │ │ ├─┬ minimatch@3.0.3 
  │ │ │ └─┬ brace-expansion@1.1.7 
  │ │ │   ├── balanced-match@0.4.2 
  │ │ │   └── concat-map@0.0.1 
  │ │ ├── once@1.4.0 
  │ │ └── path-is-absolute@1.0.1 
  │ ├── is-dir@1.0.0 
  │ └─┬ openapi-schema-validation@0.2.1 
  │   ├── jsonschema@1.0.2 
  │   ├── jsonschema-draft4@1.0.0 
  │   └── swagger-schema-official@2.0.0-bab6bed 
  ├── ip@1.1.5 
  ├─┬ js-yaml@3.8.3 
  │ ├─┬ argparse@1.0.9 
  │ │ └── sprintf-js@1.0.3 
  │ └── esprima@3.1.3 
  ├─┬ latest-version@2.0.0 
  │ └─┬ package-json@2.4.0 
  │   ├─┬ got@5.7.1 
  │   │ ├─┬ create-error-class@3.0.2 
  │   │ │ └── capture-stack-trace@1.0.0 
  │   │ ├── duplexer2@0.1.4 
  │   │ ├── is-redirect@1.0.0 
  │   │ ├── is-retry-allowed@1.1.0 
  │   │ ├── is-stream@1.1.0 
  │   │ ├── lowercase-keys@1.0.0 
  │   │ ├── node-status-codes@1.0.0 
  │   │ ├── object-assign@4.1.1 
  │   │ ├─┬ parse-json@2.2.0 
  │   │ │ └─┬ error-ex@1.3.1 
  │   │ │   └── is-arrayish@0.2.1 
  │   │ ├─┬ pinkie-promise@2.0.1 
  │   │ │ └── pinkie@2.0.4 
  │   │ ├── read-all-stream@3.1.0 
  │   │ ├─┬ readable-stream@2.2.9 
  │   │ │ ├── buffer-shims@1.0.0 
  │   │ │ ├── core-util-is@1.0.2 
  │   │ │ ├── isarray@1.0.0 
  │   │ │ ├── process-nextick-args@1.0.7 
  │   │ │ ├── string_decoder@1.0.0 
  │   │ │ └── util-deprecate@1.0.2 
  │   │ ├── timed-out@3.1.3 
  │   │ ├── unzip-response@1.0.2 
  │   │ └─┬ url-parse-lax@1.0.0 
  │   │   └── prepend-http@1.0.4 
  │   ├─┬ registry-auth-token@3.3.1 
  │   │ ├─┬ rc@1.2.1 
  │   │ │ ├── deep-extend@0.4.1 
  │   │ │ ├── ini@1.3.4 
  │   │ │ ├── minimist@1.2.0 
  │   │ │ └── strip-json-comments@2.0.1 
  │   │ └── safe-buffer@5.0.1 
  │   ├── registry-url@3.1.0 
  │   └── semver@5.3.0 
  ├─┬ morgan@1.8.1 
  │ ├── basic-auth@1.1.0 
  │ └── on-headers@1.0.1 
  ├── munin-plugin@0.0.9 
  ├── promise-queue@2.2.3 
  ├── sift@3.3.5 
  ├── swagger-ui@2.2.10 
  └── tail@1.2.1 


# pm2 unstartup
[PM2] Init System found: systemd
Removed symlink /etc/systemd/system/multi-user.target.wants/pm2-root.service.

Removed symlink /etc/systemd/system/multi-user.target.wants/pm2-root.service.

[PM2] Init file disabled.



# npm install mirakurun@latest -g --unsafe --production
                                                                                                                                            
> mirakurun@2.3.3 preinstall /usr/local/lib/node_modules/.staging/mirakurun-d2df8319
> node bin/preinstall.js


> mirakurun@2.3.3 preuninstall /usr/local/lib/node_modules/mirakurun
> node bin/preuninstall.js

[PM2] [mirakurun-server](0) ✓
┌──────────────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────────┐
│ App name         │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ watching │
├──────────────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────────┤
│ mirakurun-server │ 0  │ fork │ 0   │ stopped │ 8       │ 0      │ 0%  │ 0 B    │ disabled │
└──────────────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
[PM2] [mirakurun-server](0) ✓
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
/usr/local/bin/mirakurun -> /usr/local/lib/node_modules/mirakurun/bin/cli.sh                                                                
/usr/local/bin/mirakurun-epgdump -> /usr/local/lib/node_modules/mirakurun/bin/epgdump.js

> mirakurun@2.3.3 postinstall /usr/local/lib/node_modules/mirakurun
> node bin/postinstall.js

[PM2] Init System found: systemd
Platform systemd
Template
[Unit]
Description=PM2 process manager
Documentation=https://pm2.keymetrics.io/
After=network.target

[Service]
Type=forking
User=root
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Environment=PATH=/usr/local/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Environment=PM2_HOME=/root/.pm2
PIDFile=/root/.pm2/pm2.pid

ExecStart=/usr/local/lib/node_modules/pm2/bin/pm2 resurrect
ExecReload=/usr/local/lib/node_modules/pm2/bin/pm2 reload all
ExecStop=/usr/local/lib/node_modules/pm2/bin/pm2 kill

[Install]
WantedBy=multi-user.target

Target path
/etc/systemd/system/pm2-root.service
Command list
[ 'chmod +x /etc/systemd/system/pm2-root.service',
  'systemctl enable pm2-root',
  'systemctl start pm2-root',
  'systemctl daemon-reload',
  'systemctl status pm2-root' ]
[PM2] Writing init configuration in /etc/systemd/system/pm2-root.service
[PM2] Making script booting at startup...
>>> Executing chmod +x /etc/systemd/system/pm2-root.service
[DONE] 
>>> Executing systemctl enable pm2-root
Created symlink from /etc/systemd/system/multi-user.target.wants/pm2-root.service to /etc/systemd/system/pm2-root.service.
[DONE] 
>>> Executing systemctl start pm2-root
Job for pm2-root.service failed. See 'systemctl status pm2-root.service' and 'journalctl -xn' for details.
[ERROR] Exit code : 1
[PM2][ERROR] systemctl start pm2-root failed, see error above.
Caution: `pm2 startup` has failed. you can try fix yourself.
[PM2] Applying action restartProcessId on app [mirakurun-server](ids: 0)
[PM2] [mirakurun-server](0) ✓
┌──────────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name         │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ watching │
├──────────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ mirakurun-server │ 0  │ fork │ 11338 │ online │ 1       │ 0s     │ 0%  │ 18.0 MB   │ disabled │
└──────────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
[PM2] Saving current process list...
[PM2] Successfully saved in /root/.pm2/dump.pm2
/usr/local/lib
└── mirakurun@2.3.3 



やっぱりエラー出てしまいますorz

**Comment by kanreisa** [comment]
mirakurun は動くようになりましたよね？
電源を入れなおして自動で起動してこないようであればセルフサービスで `pm2 startup [platform]`  を実行してください
