### ISSUE TITLE
配信にUDPマルチキャストはどうでしょうか？

### ISSUE THREAD

**Issue by inyuito** [Chinachu/Mirakurun#19]
https://github.com/Chinachu/BonDriver_Mirakurun/issues/3
同上の理由(帯域削減)と遅延の関係で
TCP or UDPの切り替えが出来るよう検討していただけないでしょうか。

具体的にはconfでUDP指定時に
・視聴するPCが複数ある場合UDP
・同じ番組を選択した場合UDPマルチキャスト
・例外指定IP(Chinachuγ等)はTCP
にて送信

ご検討のほど宜しくお願いします。

**Comment by kanreisa** [comment]
フィードバックいただきありがとうございます。
Mirakurun はHTTP通信のみに限定することでAPI仕様を単純明快にし、
サーバー・クライアント共に実装・メンテナンスをしやすくしています。
一度確定したAPIについては可能な限りの間、互換性を維持していくこととしています。
また、現状の想定される利用環境において、少なくとも Mirakurun そのものは、
今のままがベストであると考えています。
何卒よろしくお願いいたします。

**Comment by inyuito** [comment]
なるほど了解しました。

UDPとTVへのデバイスキャスト
自分で作れたら作ろうと思います

HTTP UDPも有りかなとは思いましたが
上記の様な特殊な環境は少ないと思うので
今がベストかもしれませんね
ありがとうございました。
