### ISSUE TITLE
Recbond+Mirakurunで録画すると、動画の画像・音声が乱れる

### ISSUE THREAD

**Issue by allenkw** [Chinachu/Mirakurun#23]
### Environment
* Version of Mirakurun: `2.5.5`
* Version of Node: `v6.11.2`
* Version of NPM: `3.10.10`
* Platform:Ubuntu 17.04
* Architecture: x64
Chinachuγ(ubuntu17.04 on Windows10 Hyper-V)→mirakurun→recbond→BondriverProxy→BondriverproxyEX(Windows10)→Spinel(デコード実施)→PT3

### Issue
mirakurun経由で録画を実施すると
Recbond単体による録画時には見られない映像の乱れが起きます。
実行環境が特殊すぎるため、環境依存だと思いますが
解決の切り口をいただければと思います。

**Comment by allenkw** [comment]
- name: PT3-S1
  types:
  command: recpt1 --device /dev/pt3video0 --lnb 15 <channel> - -

- name: PT3-S2
  types:
  command: recpt1 --device /dev/pt3video1 --lnb 15 <channel> - -

- name: PT3-T1
  types:
    - GR
  command: recbond --driver /home/apsalus/BonDriverProxy_Linux/BonDriver_Proxy-T.so --space 0 B<channel> - -
  decoder: ~
  isDisabled: true

- name: PT3-T
  types:
    - GR
  command: recbond --driver /home/apsalus/BonDriverProxy_Linux/BonDriver_Proxy-T.so --space 0 B<channel> - -
  decoder: ~
  isDisabled: false

- name: TBS6922
  types:
    - SKY
  command: szap-s2j -c /usr/local/etc/szap-s2j.conf -l <satelite> -S 1 -p -r -M 5 -C 35 <channel>
  dvbDevicePath: /dev/dvb/adapter0/dvr0
  decoder: arib-b1-stream-test
  isDisabled: true

**Comment by allenkw** [comment]
`sr/local/var/log/mirakurun.stdout.log last 15 lines:
2|mirakuru | - - GET /api/services HTTP/1.1 200 - - 15.965 ms Chinachu/0.9.5-gamma.0 (scheduler) MirakurunClient/2.5.5 Node/v6.11.2 (linux)
2|mirakuru | - - GET /api/programs HTTP/1.1 200 - - 133.248 ms Chinachu/0.9.5-gamma.0 (scheduler) MirakurunClient/2.5.5 Node/v6.11.2 (linux)
2|mirakuru | - - GET /api/tuners HTTP/1.1 200 - - 1.446 ms Chinachu/0.9.5-gamma.0 (scheduler) MirakurunClient/2.5.5 Node/v6.11.2 (linux)
2|mirakuru | 2017-08-18T00:24:52.885+09:00 info: TunerDevice#3 process has closed with exit code=0 by signal `SIGINT` (pid=24610)
2|mirakuru | 2017-08-18T00:24:54.054+09:00 info: load config `/usr/local/etc/mirakurun/server.yml`
2|mirakuru | 2017-08-18T00:24:54.073+09:00 info: load config `/usr/local/etc/mirakurun/channels.yml`
2|mirakuru | 2017-08-18T00:24:54.085+09:00 info: load config `/usr/local/etc/mirakurun/tuners.yml`
2|mirakuru | 2017-08-18T00:24:54.087+09:00 debug: loading tuners...
2|mirakuru | 2017-08-18T00:24:54.089+09:00 debug: TunerDevice#3 initialized
2|mirakuru | 2017-08-18T00:24:54.089+09:00 info: 1 of 5 tuners loaded
2|mirakuru | 2017-08-18T00:24:54.090+09:00 debug: loading channels...
2|mirakuru | 2017-08-18T00:24:54.092+09:00 debug: loading services...
2|mirakuru | 2017-08-18T00:24:54.093+09:00 info: load db `/usr/local/var/db/mirakurun/services.json`
2|mirakuru | 2017-08-18T00:24:54.105+09:00 debug: loading programs...
2|mirakuru | 2017-08-18T00:24:54.105+09:00 info: load db `/usr/local/var/db/mirakurun/programs.json`

2|mirakuru | 2017-08-18T00:25:07.355+09:00 info: listening on http+unix://%2Fvar%2Frun%2Fmirakurun.sock
2|mirakuru | 2017-08-18T00:25:07.359+09:00 info: listening on http://192.168.1.10:40772
2|mirakuru | 2017-08-18T00:25:07.360+09:00 info: listening on http://127.0.0.1:40772
2|mirakuru | Error: listen EADDRNOTAVAIL ::1:40772
2|mirakuru |     at Object.exports._errnoException (util.js:1020:11)
2|mirakuru |     at exports._exceptionWithHostPort (util.js:1043:20)
2|mirakuru |     at Server._listen2 (net.js:1245:19)
2|mirakuru |     at listen (net.js:1294:10)
2|mirakuru |     at net.js:1404:9
2|mirakuru |     at _combinedTickCallback (internal/process/next_tick.js:83:11)
2|mirakuru |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
2|mirakuru |     at Module.runMain (module.js:606:11)
2|mirakuru |     at run (bootstrap_node.js:389:7)
2|mirakuru |     at startup (bootstrap_node.js:149:9)
2|mirakuru | Error: listen EADDRNOTAVAIL ::1:40772
2|mirakuru |     at Object.exports._errnoException (util.js:1020:11)
2|mirakuru |     at exports._exceptionWithHostPort (util.js:1043:20)
2|mirakuru |     at Server._listen2 (net.js:1245:19)
2|mirakuru |     at listen (net.js:1294:10)
2|mirakuru |     at net.js:1404:9
2|mirakuru |     at _combinedTickCallback (internal/process/next_tick.js:83:11)
2|mirakuru |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
2|mirakuru |     at Module.runMain (module.js:606:11)
2|mirakuru |     at run (bootstrap_node.js:389:7)
2|mirakuru |     at startup (bootstrap_node.js:149:9)
2|mirakuru | 2017-08-18T00:25:07.404+09:00 debug: saving services...
2|mirakuru | 2017-08-18T00:25:07.406+09:00 info: save db `/usr/local/var/db/mirakurun/services.json`
2|mirakuru | 2017-08-18T00:25:07.415+09:00 debug: saving programs...
2|mirakuru | 2017-08-18T00:25:07.431+09:00 info: save db `/usr/local/var/db/mirakurun/programs.json`
2|mirakuru | 2017-08-18T00:25:20.741+09:00 info: TSFilter has created (serviceId=24632, eventId=7888)
2|mirakuru | 2017-08-18T00:25:20.747+09:00 debug: TSFilter is waiting for serviceId=24632, eventId=7888
2|mirakuru | 2017-08-18T00:25:20.749+09:00 debug: TunerDevice#3 start stream for user `unix:1502983520736` (priority=2)...
2|mirakuru | 2017-08-18T00:25:20.749+09:00 debug: TunerDevice#3 spawn...
2|mirakuru | 2017-08-18T00:25:20.763+09:00 info: TunerDevice#3 process has spawned by command `recbond --driver /home/apsalus/BonDriverProxy_Linux/BonDriver_Proxy-T.so --space 0 B5 - -` (pid=24832)
2|mirakuru | 2017-08-18T00:25:20.766+09:00 info: TunerDevice#3 streaming to user `unix:1502983520736` (priority=2)
2|mirakuru | 2017-08-18T00:25:20.771+09:00 info: TunerDevice#3 > using driver: /home/apsalus/BonDriverProxy_Linux/BonDriver_Proxy-T.so
2|mirakuru | 2017-08-18T00:25:20.772+09:00 info: TunerDevice#3 > using Space: 0
2|mirakuru | pid = 24832
2|mirakuru | 2017-08-18T00:25:21.713+09:00 info: TunerDevice#3 > driver = /home/apsalus/BonDriverProxy_Linux/BonDriver_Proxy-T.so
2|mirakuru | 2017-08-18T00:25:21.804+09:00 info: TSFilter has created (serviceId=24632, eventId=7888)
2|mirakuru | 2017-08-18T00:25:21.804+09:00 debug: TSFilter is waiting for serviceId=24632, eventId=7888
2|mirakuru | 2017-08-18T00:25:21.804+09:00 debug: TunerDevice#3 start stream for user `unix:1502983521801` (priority=2)...
2|mirakuru | 2017-08-18T00:25:21.804+09:00 info: TunerDevice#3 streaming to user `unix:1502983521801` (priority=2)
2|mirakuru | 2017-08-18T00:25:22.068+09:00 info: TunerDevice#3 > C/N = 0.000000dB
2|mirakuru | Recording...
2|mirakuru | 2017-08-18T00:25:22.142+09:00 debug: TSFilter detected NIT PID=16
2|mirakuru | 2017-08-18T00:25:22.144+09:00 debug: TSFilter detected PMT PID=257 as serviceId=24632 (ｔｖｋ１)
2|mirakuru | 2017-08-18T00:25:22.145+09:00 debug: TSFilter parsing serviceId=24632 (ｔｖｋ１)
2|mirakuru | 2017-08-18T00:25:22.146+09:00 debug: TSFilter parsing serviceId=24633 (ｔｖｋ２)
2|mirakuru | 2017-08-18T00:25:22.151+09:00 debug: TSFilter parsing serviceId=24634 (ｔｖｋ３)
2|mirakuru | 2017-08-18T00:25:22.154+09:00 debug: TSFilter parsing serviceId=25016 (ｔｖｋワンセグ１)
2|mirakuru | 2017-08-18T00:25:22.156+09:00 debug: TSFilter detected PMT PID=258 as serviceId=24633 (ｔｖｋ２)
2|mirakuru | 2017-08-18T00:25:22.156+09:00 debug: TSFilter detected PMT PID=259 as serviceId=24634 (ｔｖｋ３)
2|mirakuru | 2017-08-18T00:25:22.156+09:00 debug: TSFilter detected PMT PID=8136 as serviceId=25016 (ｔｖｋワンセグ１)
2|mirakuru | 2017-08-18T00:25:22.163+09:00 debug: TSFilter detected NIT PID=16
2|mirakuru | 2017-08-18T00:25:22.164+09:00 debug: TSFilter detected PMT PID=257 as serviceId=24632 (ｔｖｋ１)
2|mirakuru | 2017-08-18T00:25:22.166+09:00 debug: TSFilter detected PMT PID=258 as serviceId=24633 (ｔｖｋ２)
2|mirakuru | 2017-08-18T00:25:22.166+09:00 debug: TSFilter detected PMT PID=259 as serviceId=24634 (ｔｖｋ３)
2|mirakuru | 2017-08-18T00:25:22.166+09:00 debug: TSFilter detected PMT PID=8136 as serviceId=25016 (ｔｖｋワンセグ１)
2|mirakuru | 2017-08-18T00:25:22.982+09:00 info: TSFilter is now ready for eventId=7888
2|mirakuru | 2017-08-18T00:25:22.993+09:00 info: TSFilter is now ready for eventId=7888
2|mirakuru | 2017-08-18T00:25:54.095+09:00 debug: Network#32736 EPG gathering has queued
2|mirakuru | 2017-08-18T00:25:54.097+09:00 debug: Network#32737 EPG gathering has queued
2|mirakuru | 2017-08-18T00:25:54.102+09:00 debug: Network#32295 EPG gathering has queued
2|mirakuru | 2017-08-18T00:25:54.102+09:00 debug: Network#32375 EPG gathering has queued
2|mirakuru | 2017-08-18T00:25:54.102+09:00 debug: Network#32738 EPG gathering has queued
2|mirakuru | 2017-08-18T00:25:54.103+09:00 debug: Network#32741 EPG gathering has queued
2|mirakuru | 2017-08-18T00:25:54.103+09:00 debug: Network#32739 EPG gathering has queued
2|mirakuru | 2017-08-18T00:25:54.106+09:00 debug: Network#32742 EPG gathering has queued
2|mirakuru | 2017-08-18T00:25:54.113+09:00 debug: Network#32740 EPG gathering has queued
2|mirakuru | 2017-08-18T00:25:54.113+09:00 debug: Network#32391 EPG gathering has queued
2|mirakuru | 2017-08-18T00:25:54.114+09:00 info: Network#32736 EPG gathering has started
2|mirakuru | 2017-08-18T00:26:06.412+09:00 warn: Network#32736 EPG gathering has failed [Error: no available tuners]
2|mirakuru | 2017-08-18T00:26:06.413+09:00 info: Network#32737 EPG gathering has started
2|mirakuru | 2017-08-18T00:26:18.733+09:00 warn: Network#32737 EPG gathering has failed [Error: no available tuners]
2|mirakuru | 2017-08-18T00:26:18.733+09:00 info: Network#32295 EPG gathering has started
2|mirakuru | 2017-08-18T00:26:24.841+09:00 debug: saving programs...
2|mirakuru | 2017-08-18T00:26:24.859+09:00 info: save db `/usr/local/var/db/mirakurun/programs.json`
2|mirakuru | - - GET /api/services HTTP/1.1 200 - - 29.560 ms Chinachu/0.9.5-gamma.0 (scheduler) MirakurunClient/2.5.5 Node/v6.9.2 (linux)
2|mirakuru | 2017-08-18T00:26:31.208+09:00 warn: Network#32295 EPG gathering has failed [Error: no available tuners]
2|mirakuru | 2017-08-18T00:26:31.209+09:00 info: Network#32375 EPG gathering has started
2|mirakuru | 2017-08-18T00:26:31.213+09:00 info: TSFilter has created (serviceId=null, eventId=null)
2|mirakuru | 2017-08-18T00:26:31.223+09:00 debug: TSFilter is waiting for serviceId=null, eventId=null
2|mirakuru | 2017-08-18T00:26:31.224+09:00 debug: TunerDevice#3 start stream for user `Mirakurun:getEPG()` (priority=-1)...
2|mirakuru | 2017-08-18T00:26:31.225+09:00 info: TunerDevice#3 streaming to user `Mirakurun:getEPG()` (priority=-1)
2|mirakuru | 2017-08-18T00:26:31.273+09:00 debug: TSFilter detected NIT PID=16
2|mirakuru | 2017-08-18T00:26:31.273+09:00 debug: TSFilter detected PMT PID=257 as serviceId=24632 (ｔｖｋ１)
2|mirakuru | 2017-08-18T00:26:31.275+09:00 debug: TSFilter detected PMT PID=258 as serviceId=24633 (ｔｖｋ２)
2|mirakuru | 2017-08-18T00:26:31.276+09:00 debug: TSFilter detected PMT PID=259 as serviceId=24634 (ｔｖｋ３)
2|mirakuru | 2017-08-18T00:26:31.279+09:00 debug: TSFilter detected PMT PID=8136 as serviceId=25016 (ｔｖｋワンセグ１)
2|mirakuru | - - GET /api/programs HTTP/1.1 200 - - 152.387 ms Chinachu/0.9.5-gamma.0 (scheduler) MirakurunClient/2.5.5 Node/v6.9.2 (linux)
2|mirakuru | - - GET /api/tuners HTTP/1.1 200 - - 1.135 ms Chinachu/0.9.5-gamma.0 (scheduler) MirakurunClient/2.5.5 Node/v6.9.2 (linux)
2|mirakuru | 2017-08-18T00:28:01.553+09:00 debug: TSFilter detected NIT PID=16
2|mirakuru | 2017-08-18T00:28:01.554+09:00 debug: TSFilter detected PMT PID=257 as serviceId=24632 (ｔｖｋ１)
2|mirakuru | 2017-08-18T00:28:01.554+09:00 debug: TSFilter parsing serviceId=24632 (ｔｖｋ１)
2|mirakuru | 2017-08-18T00:28:01.554+09:00 debug: TSFilter parsing serviceId=24633 (ｔｖｋ２)
2|mirakuru | 2017-08-18T00:28:01.554+09:00 debug: TSFilter parsing serviceId=24634 (ｔｖｋ３)
2|mirakuru | 2017-08-18T00:28:01.554+09:00 debug: TSFilter parsing serviceId=25016 (ｔｖｋワンセグ１)
2|mirakuru | 2017-08-18T00:28:01.567+09:00 debug: TSFilter detected NIT PID=16
2|mirakuru | 2017-08-18T00:28:01.568+09:00 debug: TSFilter detected PMT PID=257 as serviceId=24632 (ｔｖｋ１)
2|mirakuru | 2017-08-18T00:28:01.569+09:00 debug: TSFilter detected NIT PID=16
2|mirakuru | 2017-08-18T00:28:01.570+09:00 debug: TSFilter detected PMT PID=257 as serviceId=24632 (ｔｖｋ１)
2|mirakuru | 2017-08-18T00:28:01.570+09:00 debug: TSFilter detected PMT PID=258 as serviceId=24633 (ｔｖｋ２)
2|mirakuru | 2017-08-18T00:28:01.570+09:00 debug: TSFilter detected PMT PID=259 as serviceId=24634 (ｔｖｋ３)
2|mirakuru | 2017-08-18T00:28:01.570+09:00 debug: TSFilter detected PMT PID=8136 as serviceId=25016 (ｔｖｋワンセグ１)
2|mirakuru | 2017-08-18T00:28:07.415+09:00 debug: ChannelItem#'ＮＨＫ総合・東京' service scan has queued
2|mirakuru | 2017-08-18T00:28:07.417+09:00 debug: ChannelItem#'ＮＨＫＥテレ東京' service scan has queued
2|mirakuru | 2017-08-18T00:28:07.417+09:00 debug: ChannelItem#'テレ玉' service scan has queued
2|mirakuru | 2017-08-18T00:28:07.417+09:00 debug: ChannelItem#'ｔｖｋ' service scan has queued
2|mirakuru | 2017-08-18T00:28:07.417+09:00 debug: ChannelItem#'日本テレビ' service scan has queued
2|mirakuru | 2017-08-18T00:28:07.417+09:00 debug: ChannelItem#'テレビ朝日' service scan has queued
2|mirakuru | 2017-08-18T00:28:07.417+09:00 debug: ChannelItem#'ＴＢＳ' service scan has queued
2|mirakuru | 2017-08-18T00:28:07.417+09:00 debug: ChannelItem#'テレビ東京' service scan has queued
2|mirakuru | 2017-08-18T00:28:07.418+09:00 debug: ChannelItem#'フジテレビジョン' service scan has queued
2|mirakuru | 2017-08-18T00:28:07.418+09:00 debug: ChannelItem#'ＴＯＫＹＯ　ＭＸ' service scan has queued
2|mirakuru | 2017-08-18T00:30:00.719+09:00 info: TSFilter is closing because eventId=7888 has ended...
2|mirakuru | 2017-08-18T00:30:00.729+09:00 info: TSFilter is closing because eventId=7888 has ended...
2|mirakuru | 2017-08-18T00:30:01.533+09:00 debug: TSFilter detected NIT PID=16
2|mirakuru | 2017-08-18T00:30:01.541+09:00 debug: TSFilter detected PMT PID=257 as serviceId=24632 (ｔｖｋ１)
2|mirakuru | 2017-08-18T00:30:01.541+09:00 debug: TSFilter parsing serviceId=24632 (ｔｖｋ１)
2|mirakuru | 2017-08-18T00:30:01.541+09:00 debug: TSFilter parsing serviceId=24633 (ｔｖｋ２)
2|mirakuru | 2017-08-18T00:30:01.541+09:00 debug: TSFilter parsing serviceId=24634 (ｔｖｋ３)
2|mirakuru | 2017-08-18T00:30:01.541+09:00 debug: TSFilter parsing serviceId=25016 (ｔｖｋワンセグ１)
2|mirakuru | 2017-08-18T00:30:01.541+09:00 debug: TSFilter detected NIT PID=16
2|mirakuru | 2017-08-18T00:30:01.541+09:00 debug: TSFilter detected PMT PID=257 as serviceId=24632 (ｔｖｋ１)
2|mirakuru | 2017-08-18T00:30:01.542+09:00 debug: TSFilter detected NIT PID=16
2|mirakuru | 2017-08-18T00:30:01.542+09:00 debug: TSFilter detected PMT PID=257 as serviceId=24632 (ｔｖｋ１)
2|mirakuru | 2017-08-18T00:30:01.542+09:00 debug: TSFilter detected PMT PID=258 as serviceId=24633 (ｔｖｋ２)
2|mirakuru | 2017-08-18T00:30:01.542+09:00 debug: TSFilter detected PMT PID=259 as serviceId=24634 (ｔｖｋ３)
2|mirakuru | 2017-08-18T00:30:01.542+09:00 debug: TSFilter detected PMT PID=8136 as serviceId=25016 (ｔｖｋワンセグ１)
2|mirakuru | 2017-08-18T00:30:01.728+09:00 info: TSFilter has closed (serviceId=24632, eventId=7888)
2|mirakuru | 2017-08-18T00:30:01.729+09:00 debug: TunerDevice#3 end stream for user `unix:1502983520736` (priority=2)...
2|mirakuru | 2017-08-18T00:30:01.729+09:00 info: TunerDevice#3 end streaming to user `unix:1502983520736` (priority=2)
2|mirakuru | - - GET /api/programs/323752463207888/stream?decode=1 HTTP/1.1 200 - - 2309.272 ms Chinachu/0.9.5-gamma.0 (operator) MirakurunClient/2.5.5 Node/v6.11.2 (linux)
2|mirakuru | 2017-08-18T00:30:01.736+09:00 info: TSFilter has closed (serviceId=24632, eventId=7888)
2|mirakuru | 2017-08-18T00:30:01.736+09:00 debug: TunerDevice#3 end stream for user `unix:1502983521801` (priority=2)...
2|mirakuru | 2017-08-18T00:30:01.736+09:00 info: TunerDevice#3 end streaming to user `unix:1502983521801` (priority=2)
2|mirakuru | - - GET /api/programs/323752463207888/stream?decode=1 HTTP/1.1 200 - - 1250.872 ms Chinachu/0.9.5-gamma.0 (operator) MirakurunClient/2.5.5 Node/v6.9.2 (linux)
2|mirakuru | - - GET /api/services HTTP/1.1 200 - - 5.025 ms Chinachu/0.9.5-gamma.0 (scheduler) MirakurunClient/2.5.5 Node/v6.11.2 (linux)
2|mirakuru | - - GET /api/programs HTTP/1.1 200 - - 103.803 ms Chinachu/0.9.5-gamma.0 (scheduler) MirakurunClient/2.5.5 Node/v6.11.2 (linux)
2|mirakuru | - - GET /api/tuners HTTP/1.1 200 - - 1.017 ms Chinachu/0.9.5-gamma.0 (scheduler) MirakurunClient/2.5.5 Node/v6.11.2 (linux)
2|mirakuru | - - GET /api/services HTTP/1.1 200 - - 2.149 ms Chinachu/0.9.5-gamma.0 (scheduler) MirakurunClient/2.5.5 Node/v6.9.2 (linux)
2|mirakuru | - - GET /api/programs HTTP/1.1 200 - - 183.598 ms Chinachu/0.9.5-gamma.0 (scheduler) MirakurunClient/2.5.5 Node/v6.9.2 (linux)
2|mirakuru | 2017-08-18T00:36:31.227+09:00 info: TSFilter has closed (serviceId=null, eventId=null)
2|mirakuru | 2017-08-18T00:36:31.227+09:00 debug: TunerDevice#3 end stream for user `Mirakurun:getEPG()` (priority=-1)...
2|mirakuru | 2017-08-18T00:36:31.227+09:00 info: TunerDevice#3 end streaming to user `Mirakurun:getEPG()` (priority=-1)
2|mirakuru | 2017-08-18T00:36:31.228+09:00 info: Network#32375 EPG gathering has finished
2|mirakuru | 2017-08-18T00:36:31.228+09:00 info: Network#32738 EPG gathering has started
2|mirakuru | 2017-08-18T00:36:31.248+09:00 info: TSFilter has created (serviceId=null, eventId=null)
2|mirakuru | 2017-08-18T00:36:31.252+09:00 debug: TSFilter is waiting for serviceId=null, eventId=null
2|mirakuru | 2017-08-18T00:36:31.252+09:00 debug: TunerDevice#3 start stream for user `Mirakurun:getEPG()` (priority=-1)...
2|mirakuru | 2017-08-18T00:36:31.253+09:00 debug: TunerDevice#3 kill...
2|mirakuru | 2017-08-18T00:36:31.269+09:00 info: TunerDevice#3 process has closed with exit code=0 by signal `SIGTERM` (pid=24832)
2|mirakuru | 2017-08-18T00:36:31.370+09:00 debug: TunerDevice#3 released
2|mirakuru | 2017-08-18T00:36:31.371+09:00 debug: TunerDevice#3 spawn...
2|mirakuru | 2017-08-18T00:36:31.398+09:00 info: TunerDevice#3 process has spawned by command `recbond --driver /home/apsalus/BonDriverProxy_Linux/BonDriver_Proxy-T.so --space 0 B12 - -` (pid=25961)

**Comment by allenkw** [comment]
chinachuのストリーミングでは乱れません。
録画したもののみ乱れるようです。
ほかに調査の役に立つものがあればご教示いただきたく。

**Comment by misak1** [comment]
recbond単体ではストリーミングの乱れは発生しないのですか？

質問に質問で返すようで申し訳ないのですが、
私のところでも同じようなことが起きており、recpt1単体では問題なく録画出来るのに、
Chinachuのアップデートに伴いMirakurunを使って録画した場合に録画が乱れる現象が起きています。

**Comment by kanreisa** [comment]
@allenkw 

```
Error: listen EADDRNOTAVAIL ::1:40772
```
起動時にこのようなエラーが出ているようですが、`mirakurun config server` で下記設定を追加することで解消できます。
```
disableIPv6: true
```
****
頂戴したログを見る限りその他エラー等発生していないようですので、その他の部分でドロップしているのかもしれません。仮想環境との事ですので、なかなかお勧めできる環境ではないことは確かです・・・。`vmstat`等でのトラブルシューティングが難しい場合、もう既にお試しかもしれませんが、WindowsでMirakurunを動かすと良いかもしれません。

**Comment by allenkw** [comment]
@misak1 recbond単体ではストリーミングに乱れはありません。おっしゃる通り、chinachu無印の場合はmirakurun導入なしでchinachuから直接、recbondを実行していました。
chinachuγにアップデートするにあたりmirakurunを同時に導入してから現象が起きている状況です。

**Comment by allenkw** [comment]
@kanreisa ipv6の設定を適用し、errorが出ないこと確認できました。ありがとうございます。
その他エラーはない旨承知しました。
推奨環境ではないことはわかっていたので・・・直せたらと思い起票させてもらいました。。

一縷の望みをかけてですが、
カードリーダーをWindows側に設けているため、decodeをWindows側で実施したうえで.Linuxに対してTSを送信しています、
mirakurun config tunnersの設定でdecodeを「~」しています。
mirakurunの動作としてあらかじめdecodeされているTSの録画は可能でしょうか。

**Comment by kanreisa** [comment]
decodeされていたとしても一部のパケットに欠けや変な改変んがある場合は正常に動作できなくなる可能性があります。エラーは出ていないため見た目上は正常です。

ホストマシン(Windows)でMirakurunを動かした方が速いかと思います。

**Comment by allenkw** [comment]
Windows でMirakurun 動かすことで、正常に録画できました。
ありがとうございました。

私以外にも同じ現象が起きているため、
原因を明確にできなかったのが、少し心残りです。

以上です。
これからも愛用させていただきます。
今後ともお世話になります。
