### ISSUE TITLE
EPGデータの文字化け

### ISSUE THREAD

**Issue by aspyge** [Chinachu/Mirakurun#26]
### Environment
* Version of Mirakurun: `2.5.7`
* Version of Node: `v6.10.3`
* Version of NPM: `3.10.10`
* Platform:Ubuntu `16.04`
* Architecture: x64

### Issue
EPGの番組表データが一部文字化けしています
当方の環境ではUTF-8のテキストデータとしてprograms.jsonを開き、`\u0`を検索すると異常箇所がヒットします

**Comment by hideo54** [comment]
同様の現象 ( `�\u0`~) を確認した他、まれに

> 「ラブライブ!サンシャイン!!Aqわ　をん　ご　よ　ぬわ　ゅぬら　ゅぁ　～びめられらゎょ　　わ　　よゅ　び　ゎんよらゎゅ～」
(正しくは「ラブライブ！サンシャイン!!Aqours 4th LoveLive! ～Sailing to the Sunshine～」)

(出典: 2018/11/25 9:30~ TV東京/大阪で放送予定の「ＪＡＰＡＮ　ＣＯＵＮＴＤＯＷＮ」)

のように、部分的に異なった文字が現れる現象も確認しました。
上の例では、UTF-8 で `XX` (16進数) と表される文字が ISO-2022-JP で `24XX` (16進数) と表される文字に変換されていることから、文字コード変換のあたりでバグがあると推測します。
(例: 「n」(UTF-8: `6E`) →「ゎ」(ISO-2022-JP: `246E`) )

programs.json で「ゎ」で検索すると同様の異常箇所を探しやすいです。

これ以上の詳細な調査ができておらず恐縮ですが、とりあえず報告させていただきました。

### Environment
* Version of Mirakurun: `2.7.4`
* Version of Node: `v10.12.0`
* Version of NPM: `6.4.1`
* Platform: Debian 9.5
* Architecture: x64
