### ISSUE TITLE
空の動画ファイルが生成される

### ISSUE THREAD

**Issue by DABURUTTI** [Chinachu/Mirakurun#27]
### Environment
 Environment
* Version of Mirakurun: `2.5.5`
* Version of Node: `v6.5.0`
* Version of NPM: `3.10.3`
* Platform:`Linux-Ubuntu`
* Architecture: x64

## 空の録画ファイルが生成される、さらに架空の録画データが無限生成される

Chinachuを開くと録画件数が膨大になっていて、なにが録画されたのか確認したところ
録画済みのページに同じタイトルが無限生成されていました
実際にファイルを探したところ、空のファイルが一つ生成されているだけで、それを消したうえでクリーンアップを行ったところ無限生成されていたタイトルはすべて消えました

なお、recpt1コマンドで直接録画コマンドを入力すると正常に録画されました

よろしくお願いいたします。

### Screenshot
![snapcrab_noname_2018-1-7_1-45-46_no-00](https://user-images.githubusercontent.com/24826149/34708044-2b7e46be-f554-11e7-8093-dd0e83508376.png)

Chinachu開発者様に感謝申し上げます。

**Comment by kanreisa** [comment]
> 空の録画ファイルが生成される

下記のような原因が考えられますが、何が起きたのかはログを確認してください。

* Mirakurun が正常に動作していない
* チューナーが足りていない

> さらに架空の録画データが無限生成される

Chinachu の長らく放置されているバグです。

**Comment by kanreisa** [comment]
Chinachu 側の問題のため Close します
