### ISSUE TITLE
インストールエラー(windows10home)

### ISSUE THREAD

**Issue by cuckoozero** [Chinachu/Mirakurun#28]
### Environment
* Version of Mirakurun: `2.5.7`
* Version of Node: `v6.12.3`
* Version of NPM: `3.10.10`
* Platform: windows10 [home]
* Architecture: x64

### Issue
Mirakurunのインストールでエラーが出てしまいます。
windows非サポートなのは承知してますが、対応していただけたらありがたいです。
[npm-debug.log](https://github.com/Chinachu/Mirakurun/files/1628135/npm-debug.log)

**Comment by kanreisa** [comment]
npm のログファイルだけではコンソールの出力が不完全なようですので、
もう一度実行していただき、出力を貼っていただけますでしょうか？

**Comment by cuckoozero** [comment]
ありがとうございます。
コンソールは実行後そのままにしていたので貼ってみます。

PS C:\> npm install @kanreisa/winser -g
C:\Users\cuckoo\AppData\Roaming\npm\winser -> C:\Users\cuckoo\AppData\Roaming\npm\node_modules\@kanreisa\winser\bin\wins
er
C:\Users\cuckoo\AppData\Roaming\npm
`-- @kanreisa/winser@1.0.2
  +-- async@0.9.0
  `-- stdio@0.2.2

PS C:\> npm install mirakurun -g --production

> mirakurun@2.5.7 preinstall C:\Users\cuckoo\AppData\Roaming\npm\node_modules\.staging\mirakurun-a2266e18
> node bin/preinstall.js

The service for "mirakurun" was removed.
C:\Users\cuckoo\AppData\Roaming\npm\mirakurun-epgdump -> C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun\bin\
epgdump.js
C:\Users\cuckoo\AppData\Roaming\npm\mirakurun -> C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun\bin\cli.sh

> mirakurun@2.5.7 postinstall C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun
> node bin/postinstall.js

Version: node@v6.12.3 [OK]
Version: winser@v1.0.2
 [OK]
Use start command "node.exe bin\init.win32.js".
The program "mirakurun" was installed as a service.
mirakurun: Unexpected status SERVICE_START_PENDING in response to START control.

{ Error: Command failed: "C:\Users\cuckoo\AppData\Roaming\npm\node_modules\@kanreisa\winser\bin\nssm64.exe" start "mirak
urun"
mirakurun: Unexpected status SERVICE_START_PENDING in response to START control.

    at ChildProcess.exithandler (child_process.js:199:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '"C:\\Users\\cuckoo\\AppData\\Roaming\\npm\\node_modules\\@kanreisa\\winser\\bin\\nssm64.exe" start "mirakurun" '
 }
child_process.js:496
    throw err;
    ^

Error: Command failed: winser.cmd -i -a --startuptype delayed --startcmd node.exe bin\init.win32.js --set AppPriority AB
OVE_NORMAL_PRIORITY_CLASS --set Type SERVICE_WIN32_OWN_PROCESS --set AppStdout C:\Users\cuckoo\AppData\Local\Mirakurun\s
tdout --set AppStderr C:\Users\cuckoo\AppData\Local\Mirakurun\stderr --env LOG_STDOUT=C:\Users\cuckoo\AppData\Local\Mira
kurun\stdout --env LOG_STDERR=C:\Users\cuckoo\AppData\Local\Mirakurun\stderr --env USERPROFILE=C:\Users\cuckoo --env LOC
ALAPPDATA=C:\Users\cuckoo\AppData\Local --env USING_WINSER=1
    at checkExecSyncError (child_process.js:473:13)
    at Object.execFileSync (child_process.js:493:13)
    at Object.<anonymous> (C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun\bin\postinstall.js:153:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "mirakurun" "-g" "--production"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! mirakurun@2.5.7 postinstall: `node bin/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirakurun@2.5.7 postinstall script 'node bin/postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mirakurun package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mirakurun
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mirakurun
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

また何か不足があるようでしたら教えてください。

**Comment by kanreisa** [comment]
次を試してみてください:

* [Node.js 8](https://nodejs.org/en/) をインストールしてみる
* Windows Update してみる (お使いの Windows 10 は少し古いようです)

**Comment by cuckoozero** [comment]
windows10は録画サーバーとして使用していたので再起動抑制のためにwindows updateを切っていました。
昨日オンラインアップデートを行いましたが失敗し、まだ更新できていません。
先にnode.js 8.9.4をインストールしてMirakurunをインストールしようとした際のコンソールとログを張らせていただきます。
宜しくお願いします。

PS C:\> npm -v
5.6.0
PS C:\> npm install @kanreisa/winser -g
C:\Users\cuckoo\AppData\Roaming\npm\winser -> C:\Users\cuckoo\AppData\Roaming\npm\node_modules\@kanreisa\winser\bin\wins
er
+ @kanreisa/winser@1.0.2
added 3 packages in 4.447s
PS C:\> npm install mirakurun -g --production

> mirakurun@2.5.7 preinstall C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun
> node bin/preinstall.js

The service for "mirakurun" was removed.
C:\Users\cuckoo\AppData\Roaming\npm\mirakurun -> C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun\bin\cli.sh
C:\Users\cuckoo\AppData\Roaming\npm\mirakurun-epgdump -> C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun\bin\
epgdump.js

> mirakurun@2.5.7 postinstall C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun
> node bin/postinstall.js

Version: node@v8.9.4 [OK]
Version: winser@v1.0.2
 [OK]
Use start command "node.exe bin\init.win32.js".
The program "mirakurun" was installed as a service.
mirakurun: Unexpected status SERVICE_START_PENDING in response to START control.

{ Error: Command failed: "C:\Users\cuckoo\AppData\Roaming\npm\node_modules\@kanreisa\winser\bin\nssm64.exe" start "mirak
urun"
mirakurun: Unexpected status SERVICE_START_PENDING in response to START control.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '"C:\\Users\\cuckoo\\AppData\\Roaming\\npm\\node_modules\\@kanreisa\\winser\\bin\\nssm64.exe" start "mirakurun" '
 }
child_process.js:624
    throw err;
    ^

Error: Command failed: winser.cmd -i -a --startuptype delayed --startcmd node.exe bin\init.win32.js --set AppPriority AB
OVE_NORMAL_PRIORITY_CLASS --set Type SERVICE_WIN32_OWN_PROCESS --set AppStdout C:\Users\cuckoo\AppData\Local\Mirakurun\s
tdout --set AppStderr C:\Users\cuckoo\AppData\Local\Mirakurun\stderr --env LOG_STDOUT=C:\Users\cuckoo\AppData\Local\Mira
kurun\stdout --env LOG_STDERR=C:\Users\cuckoo\AppData\Local\Mirakurun\stderr --env USERPROFILE=C:\Users\cuckoo --env LOC
ALAPPDATA=C:\Users\cuckoo\AppData\Local --env USING_WINSER=1
    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at Object.<anonymous> (C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun\bin\postinstall.js:153:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirakurun@2.5.7 postinstall: `node bin/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirakurun@2.5.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cuckoo\AppData\Roaming\npm-cache\_logs\2018-01-15T11_10_54_406Z-debug.log
[2018-01-15T11_10_54_406Z-debug.log](https://github.com/Chinachu/Mirakurun/files/1631422/2018-01-15T11_10_54_406Z-debug.log)

**Comment by cuckoozero** [comment]
windows10のアップデートに成功したためもう一度インストールを試みましたがやはりエラーになるようです。
お手数おかけします。

PS C:\> npm install @kanreisa/winser -g
C:\Users\cuckoo\AppData\Roaming\npm\winser -> C:\Users\cuckoo\AppData\Roaming\npm\node_modules\@kanreisa\winser\bin\winser
+ @kanreisa/winser@1.0.2
updated 1 package in 12.323s
PS C:\> npm install mirakurun -g --production

> mirakurun@2.5.7 preinstall C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun
> node bin/preinstall.js

C:\Users\cuckoo\AppData\Roaming\npm\mirakurun -> C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun\bin\cli.sh
C:\Users\cuckoo\AppData\Roaming\npm\mirakurun-epgdump -> C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun\bin\epgdump.js

> mirakurun@2.5.7 postinstall C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun
> node bin/postinstall.js

Version: node@v8.9.4 [OK]
Version: winser@v1.0.2
 [OK]
Use start command "node.exe bin\init.win32.js".
The program "mirakurun" was installed as a service.
mirakurun: Unexpected status SERVICE_START_PENDING in response to START control.

{ Error: Command failed: "C:\Users\cuckoo\AppData\Roaming\npm\node_modules\@kanreisa\winser\bin\nssm64.exe" start "mirakurun"
mirakurun: Unexpected status SERVICE_START_PENDING in response to START control.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '"C:\\Users\\cuckoo\\AppData\\Roaming\\npm\\node_modules\\@kanreisa\\winser\\bin\\nssm64.exe" start "mirakurun" ' }
child_process.js:624
    throw err;
    ^

Error: Command failed: winser.cmd -i -a --startuptype delayed --startcmd node.exe bin\init.win32.js --set AppPriority ABOVE_NORMAL_PRIORITY_CLASS --set Type SERVICE_WIN32_OWN_PROCESS --set AppStdout C:\Users\cuckoo\AppData\Local\Mirakurun\stdout --set AppStderr C:\Users\cuckoo\AppData\Local\Mirakurun\stderr --env LOG_STDOUT=C:\Users\cuckoo\AppData\Local\Mirakurun\stdout --env LOG_STDERR=C:\Users\cuckoo\AppData\Local\Mirakurun\stderr --env USERPROFILE=C:\Users\cuckoo --env LOCALAPPDATA=C:\Users\cuckoo\AppData\Local --env USING_WINSER=1
    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at Object.<anonymous> (C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun\bin\postinstall.js:153:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
npm WARN rollback Rolling back mirakurun@2.5.7 failed (this is probably harmless): EBUSY: resource busy or locked, rmdir 'C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirakurun@2.5.7 postinstall: `node bin/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirakurun@2.5.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cuckoo\AppData\Roaming\npm-cache\_logs\
[2018-01-21T03_51_35_812Z-debug.log](https://github.com/Chinachu/Mirakurun/files/1649515/2018-01-21T03_51_35_812Z-debug.log)
2018-01-21T03_51_35_812Z-debug.log

**Comment by kanreisa** [comment]
> `SERVICE_START_PENDING`

サービスの開始操作で失敗している事はログからわかりました。 

```
npm uninstall mirakurun -g
sc delete mirakurun
```
を実行してから再実行してみてください。
正直、こちらの環境で再現しないのでどうやったら直るのかは分かりません。

**Comment by cuckoozero** [comment]
すいません
早速ありがとうございます。
指示通りに実行してみました。
よろしくお願いします。

PS C:\> npm uninstall mirakurun -g

> mirakurun@2.5.7 preuninstall C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun
> node bin/preuninstall.js

removed 1 package in 9.073s
PS C:\> sc delete mirakurun
PS C:\> npm install mirakurun -g --production

> mirakurun@2.5.7 preinstall C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun
> node bin/preinstall.js

C:\Users\cuckoo\AppData\Roaming\npm\mirakurun-epgdump -> C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun\bin\epgdump.js
C:\Users\cuckoo\AppData\Roaming\npm\mirakurun -> C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun\bin\cli.sh

> mirakurun@2.5.7 postinstall C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun
> node bin/postinstall.js

Version: node@v8.9.4 [OK]
Version: winser@v1.0.2
 [OK]
Use start command "node.exe bin\init.win32.js".
The program "mirakurun" was installed as a service.
mirakurun: Unexpected status SERVICE_START_PENDING in response to START control.

{ Error: Command failed: "C:\Users\cuckoo\AppData\Roaming\npm\node_modules\@kanreisa\winser\bin\nssm64.exe" start "mirakurun"
mirakurun: Unexpected status SERVICE_START_PENDING in response to START control.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '"C:\\Users\\cuckoo\\AppData\\Roaming\\npm\\node_modules\\@kanreisa\\winser\\bin\\nssm64.exe" start "mirakurun" ' }
child_process.js:624
    throw err;
    ^

Error: Command failed: winser.cmd -i -a --startuptype delayed --startcmd node.exe bin\init.win32.js --set AppPriority ABOVE_NORMAL_PRIORITY_CLASS --set Type SERVICE_WIN32_OWN_PROCESS --set AppStdout C:\Users\cuckoo\AppData\Local\Mirakurun\stdout --set AppStderr C:\Users\cuckoo\AppData\Local\Mirakurun\stderr --env LOG_STDOUT=C:\Users\cuckoo\AppData\Local\Mirakurun\stdout --env LOG_STDERR=C:\Users\cuckoo\AppData\Local\Mirakurun\stderr --env USERPROFILE=C:\Users\cuckoo --env LOCALAPPDATA=C:\Users\cuckoo\AppData\Local --env USING_WINSER=1
    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at Object.<anonymous> (C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun\bin\postinstall.js:153:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
npm WARN rollback Rolling back mirakurun@2.5.7 failed (this is probably harmless): EBUSY: resource busy or locked, rmdir 'C:\Users\cuckoo\AppData\Roaming\npm\node_modules\mirakurun'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirakurun@2.5.7 postinstall: `node bin/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirakurun@2.5.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cuckoo\AppData\Roaming\npm-cache\_logs\
[2018-01-21T04_21_31_718Z-debug.log](https://github.com/Chinachu/Mirakurun/files/1649530/2018-01-21T04_21_31_718Z-debug.log)
2018-01-21T04_21_31_718Z-debug.log

**Comment by kanreisa** [comment]
やはり再現しないので分かんないです。
Event Viewer 等で原因を探ってください。

**Comment by cuckoozero** [comment]
イベントビューアを探ったところ下記のエラーが記録されていました。
究明のお役に立ちますでしょうか？

ログの名前:         Application
ソース:           nssm
日付:            2018/01/21 13:21:26
イベント ID:       1030
タスクのカテゴリ:      なし
レベル:           警告
キーワード:         クラシック
ユーザー:          N/A
コンピューター:       rec-server
説明:
Registry key AppDirectory is unset for service mirakurun. Assuming startup directory C:\WINDOWS.
イベント XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="nssm" />
    <EventID Qualifiers="32768">1030</EventID>
    <Level>3</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-01-21T04:21:26.723205100Z" />
    <EventRecordID>1442</EventRecordID>
    <Channel>Application</Channel>
    <Computer>rec-server</Computer>
    <Security />
  </System>
  <EventData>
    <Data>AppDirectory</Data>
    <Data>mirakurun</Data>
    <Data>C:\WINDOWS</Data>
  </EventData>
</Event>

**Comment by kanreisa** [comment]
Win 10はアップグレードしたものですか？
環境変数などが足りてないのかもしれません。
クリーンインストールは試しましたか？(別のHDDなどを使えば既存の環境を壊しません)
自分でソースからビルドして、あるいはサービスとして動かすことを諦めるという手もあります。
いずれにしても Windows サポートは当面の間  Experimental です。
トラブルシューティング含め自己解決できないとご利用するのは厳しいのかなと思います。
コミュニティに助けを求める場合は Slack などをご活用ください。

**Comment by cuckoozero** [comment]
windows10はアップグレードをして最新版になっていると思われます。
クリーンインストールはまだ試していません。

{ Error: Command failed: "C:\Users\cuckoo\AppData\Roaming\npm\node_modules@kanreisa\winser\bin\nssm64.exe" start "mirakurun"
のエラーですが、そのままコンソールにコピーして実行するとやはりエラーになりますが、パスのダブルクォートを取って実行してみるとエラー無くnssm service installerが起動します。

PS C:\> "C:\Users\cuckoo\AppData\Roaming\npm\node_modules\@kanreisa\winser\bin\nssm64.exe" install mirakurun
発生場所 行:1 文字:84
+ ... ing\npm\node_modules\@kanreisa\winser\bin\nssm64.exe" install mirakur ...
+                                                           ~~~~~~~
式またはステートメントのトークン 'install' を使用できません。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

PS C:\> C:\Users\cuckoo\AppData\Roaming\npm\node_modules\@kanreisa\winser\bin\nssm64.exe install mirakurun
PS C:\>

PowerShellのクセでしょうか？

しかしながらExperimentalとのことで、それにもかかわらずこれまでご対応いただき感謝しています。
いつかExperimentalが取れる日を期待して待ちたいと思います。
ありがとうございました。

**Comment by kanreisa** [comment]
Windows 8.1 等からアップグレードしたものか？という意味です。
私の知る限り普通の方は特に問題なくインストールできているようですので、このエラーは初めて知りました。
クライアント版 Windows の用途からは外れているのは間違いないので、期待はしないでください。 
何しろ開発者が Windows 版をドックフーディング出来ていないのです。(´･_･`)

**Comment by cuckoozero** [comment]
おっしゃる通り、win7あたりから順番にアップグレードしてきています。
確かに一度クリーンインストールもしてみるべきですね。

**Comment by advancedbear** [comment]
1ヶ月近く前のclosedなissueにコメントして申し訳ありませんが、同様の症状が発生しましたが解決出来たので情報共有させて頂きます。
恐らく、インストールに際して何処かのサイト等を参考にしてインストールされていると思いますが、winserのインストール時に
`npm install @kanreisa/winser -g`
を実行してインストールを行ってしまうと、現行バージョンのMirakurunではインストールに失敗するようです。
cuckoozero氏のCommand failed時のエラーも`~npm\node_modules@kanreisa\winser~`となっているので、恐らく同様のエラーなのかなと思われます。

winserをインストールする際は、
`npm install winser@1.0.3 -g`
もしくは
`npm install winser -g`
のどちらかでなければならないようです。

**Comment by cuckoozero** [comment]
advancedbearさん、情報ありがとうございます。
おっしゃる通りの方法で正常にインストールできました。
readmeのほうも既に修正されているようですね。

ありがとうございました。助かりました。

**Comment by ohmsa** [comment]
Environment
Version of Mirakurun: 
Version of Node: v8.16.1
Version of NPM: 6.4.1
Platform: windows10 [professional]
Architecture: x64
Issue

私も同じくパーミッション関係？のエラーが発生しております。Windows10は新規でインストールしており、エラーのため再度新規インストールしました。

**Comment by ohmsa** [comment]
Environment
Version of Mirakurun:
Version of Node: v8.16.1
Version of NPM: 6.4.1
Platform: windows10 [professional]
Architecture: x64
Issue
私も同じくパーミッション関係？のエラーが発生しております。Windows10は新規でインストールしており、エラーのため再度新規インストールしました。
最初はGithubのリンクから飛んだ先のNodeが10系だったから？と思い手動でNode　v8.16.1をインストールしました。その他のインストール手順は公式通りに
・npm install winser@1.0.3 -g
・npm install mirakurun@latest -g --production
で、winserは入ったようです。

一年前のIssueで恐縮ですが、お知恵を拝借したく存じます。

PS C:\Windows\system32> npm install winser@1.0.3 -g
C:\Users\myRecServer\AppData\Roaming\npm\winser -> C:\Users\myRecServer\AppData\Roaming\npm\node_modules\winser\bin\winser
+ winser@1.0.3
added 3 packages from 3 contributors in 25.248s
PS C:\Windows\system32> npm install mirakurun@latest -g --production

> mirakurun@2.11.0 preinstall C:\Users\myRecServer\AppData\Roaming\npm\node_modules\mirakurun
> node bin/preinstall.js

C:\Users\myRecServer\AppData\Roaming\npm\mirakurun-epgdump -> C:\Users\myRecServer\AppData\Roaming\npm\node_modules\mirakurun\bin\epgdump.js
C:\Users\myRecServer\AppData\Roaming\npm\mirakurun -> C:\Users\myRecServer\AppData\Roaming\npm\node_modules\mirakurun\bin\cli.sh

> core-js@2.6.9 postinstall C:\Users\myRecServer\AppData\Roaming\npm\node_modules\mirakurun\node_modules\core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> mirakurun@2.11.0 postinstall C:\Users\myRecServer\AppData\Roaming\npm\node_modules\mirakurun
> node bin/postinstall.js && opencollective-postinstall

Version: node@v8.16.1 [OK]
Version: winser@v1.0.3 [OK]
Use start command "node.exe bin\init.win32.js".
The program "mirakurun" was installed as a service.
m i r a k u r u n :   U n e x p e c t e d   s t a t u s   S E R V I C E _ S T A R T _ P E N D I N G   i n   r e s p o n   e   t o   S T A R T   c o n t r o l .

{ Error: Command failed: "C:\Users\myRecServer\AppData\Roaming\npm\node_modules\winser\bin\nssm64.exe" start "mirakurun"
m i r a k u r u n :   U n e x p e c t e d   s t a t u s   S E R V I C E _ S T A R T _ P E N D I N G   i n   r e s p o n   e   t o   S T A R T   c o n t r o l .

    at ChildProcess.exithandler (child_process.js:281:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '"C:\\Users\\myRecServer\\AppData\\Roaming\\npm\\node_modules\\winser\\bin\\nssm64.exe" start "mirakurun" ' }
child_process.js:630
    throw err;
    ^

Error: Command failed: winser.cmd -i -a --startuptype auto --startcmd node.exe bin\init.win32.js --set AppPriority ABOVE_NORMAL_PRIORITY_CLASS --set Type SERVICE_WIN32_OWN_PROCESS --set AppStdout C:\Users\myRecServer\AppData\Local\Mirakurun\stdout --set AppStderr C:\Users\myRecServer\AppData\Local\Mirakurun\stderr --env USERPROFILE=C:\Users\myRecServer --env LOCALAPPDATA=C:\Users\myRecServer\AppData\Local --env USING_WINSER=1
    at checkExecSyncError (child_process.js:607:13)
    at Object.execFileSync (child_process.js:627:13)
    at Object.<anonymous> (C:\Users\myRecServer\AppData\Roaming\npm\node_modules\mirakurun\bin\postinstall.js:154:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirakurun@2.11.0 postinstall: `node bin/postinstall.js && opencollective-postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirakurun@2.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myRecServer\AppData\Roaming\npm-cache\_logs\2019-09-03T
[2019-09-03T03_38_42_369Z-debug.log](https://github.com/Chinachu/Mirakurun/files/3567684/2019-09-03T03_38_42_369Z-debug.log)
03_38_42_369Z-debug.log

**Comment by ohmsa** [comment]
すみません。node.jsを8.9.4にしたらインストールできました。

8.16や10系は未対応ですね。確認し忘れておりました。お騒がせいたしました。
