### ISSUE TITLE
Mirakurun UIに接続できない

### ISSUE THREAD

**Issue by ohmsa** [Chinachu/Mirakurun#29]
### Environment
* Version of Mirakurun: `2.5.7`
* Version of Node: `v6.5.0`
* Version of NPM: `5.6.0`
* Platform:Windows 10 pro
* Architecture: x64

### Issue
TVTest/EDCB環境で使用しておりました。
今回Node.jsで動くということでMirakurunを試してみようと思いインストールしたのですが、
Mirakurun UIにて接続が確認できません。
Connection failedと出てしまいます。

・MirakurunUIには自身のIPアドレスおよびMirakurunにて使用するポート番号を指定しております。
・ポート自体はTCP/UDP送受信ともに開けております。
・タスクマネージャによるとMirakurunサービスは実行中のようです。

何か設定忘れ等ございますでしょうか。
AppData\Local\Mirakurun　内のエラーログを添付いたします。

[stderr.txt](https://github.com/Chinachu/Mirakurun/files/1715070/stderr.txt)

**Comment by kanreisa** [comment]
エラーを読んでね。

https://ja.wikipedia.org/wiki/YAML

**Comment by ohmsa** [comment]
返信ありがとうございます。

エラーを見るに
YAMLException: incomplete explicit mapping pair; a key node is missed
コンポーネントが足りていないようです。
Winserを入れたりnpm install -g npm-install-missingをやってみたのですが、やはり同じエラーの様子。

必須のコンポーネントはWinserだけでしょうか。または、エラーログの読み方を間違っているのでしょうか。

**Comment by kanreisa** [comment]
書式エラーですよ。英語を読んでね。
