### ISSUE TITLE
アップデートでエラーorz

### ISSUE THREAD

**Issue by nomiu26** [Chinachu/Mirakurun#30]
userでも同じだったのでrootで実行してみたのですが以下のエラーで悩んでます。
何が原因なのでしょうか？バージョンが新しすぎる！？

# npm install mirakurun -g --unsafe --production
                                                                                                                                                        
> mirakurun@2.7.0 preinstall /usr/local/lib/node_modules/mirakurun
> node bin/preinstall.js

/usr/local/bin/mirakurun -> /usr/local/lib/node_modules/mirakurun/bin/cli.sh
/usr/local/bin/mirakurun-epgdump -> /usr/local/lib/node_modules/mirakurun/bin/epgdump.js
                                                                                                                                                        
> mirakurun@2.7.0 postinstall /usr/local/lib/node_modules/mirakurun
> node bin/postinstall.js

Version: node@v9.5.0 [NG] Expected: ^8.9.4 < 9
npm ERR! code ELIFECYCLE                                                                                                                                
npm ERR! errno 1
npm ERR! mirakurun@2.7.0 postinstall: `node bin/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mirakurun@2.7.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-21T23_26_44_480Z-debug.log
root@debian:~# node -v
v9.5.0

**Comment by kanreisa** [comment]
はい。`^8.9.4 < 9`と書かれている通りとなります。

こちらでも注意書きを太字で書いています。
https://github.com/Chinachu/Chinachu/wiki/Gamma-Installation-V2

よろしくお願いいたします。
