### ISSUE TITLE
mirarkun新規インストールとpm2バージョン

### ISSUE THREAD

**Issue by izenizen** [Chinachu/Mirakurun#36]
### Environment
* Version of Mirakurun: `2.7.0`
* Version of Node: `v8.11.3`
* Version of NPM: `5.6.0`
* Platform: ubuntu 16.04 LTS
* Architecture: x64

### Issue
Version: node@v8.11.3 [OK]
3.0.0

Version: pm2@3.0.0 [NG] Expected: >=2.4.0 <3.0.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirakurun@2.7.0 postinstall: `node bin/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirakurun@2.7.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hide/.npm/_logs/2018-07-11T03_30_00_648Z-debug.log

PM2のバージョンが3.0.0以下と指定になっていますが、現在の標準では`sudo npm install pm2 -g`の結果、PM2が3.0.0がインストールされてしまいます。
PM2のVersion Historyを見ますと、3.0.0は7 days agoでアップグレードしてしまったようです。
一旦、pm2を2.10.4に落としてインストールしますが、スクリプトのご変更をお願いいたします。

**Comment by izenizen** [comment]
yamakenさんのおっしゃる通りですね。
みなさんがログ読んでくれれば良いだけです。
読まないようなやつはこの世界に入ってくるなと言うのが一番簡単だと思います。
そうすると、ちょっと親切にするならばreadme.meとか、公式のあちこちに散りばめて書かれているインストール方法の記載を直して、バージョン指定が必要ですと言うか、スクリプトを直すかでしょう。
インストールできない！と大騒ぎされる方々への対応がウザくなられるのがしんどいのかな思った次第です。

**Comment by kanreisa** [comment]
updated

**Comment by yamaken-sapporo** [comment]
私はどっちかっていうと簡単に「スクリプトのご変更をお願いいたします。」
の記述の方がどうかと。
PM2メジャーバージョンアップしてますよね？
動作検証して問題ないという判断で書いたのですか？
であればバージョン判定だけ直せばいいので、ご自身でプルリクまですれば良いのでは？と思った次第
