### ISSUE TITLE
SKyperfect with 11.300 Ghz LNB

### ISSUE THREAD

**Issue by juesus** [Chinachu/Mirakurun#39]
### Environment
* Version of Mirakurun: `2.x.x`
* Version of Node: `v6.x.x`
* Version of NPM: `x.x.x`
* Platform:
* Architecture: x64

### Issue
I can not get SKY signal (124E,128E)
I use TBS6922 with  LoF 11.300 Ghz LNB
How can I change it LoF
...

**Comment by kanreisa** [comment]
this is not QA forum.
