### ISSUE TITLE
[要望] logを出力しない設定値

### ISSUE THREAD

**Issue by epgdatacapbon** [Chinachu/Mirakurun#41]
現在、最低でもFATALのlogは出力するようになっておりますが、
可能でしたらlogを全く出力しない設定値を作って頂けませんでしょうか。

**Comment by kanreisa** [comment]
@epgdatacapbon `logLevel` を `-2` にしてみてはいかがでしょうか?

**Comment by epgdatacapbon** [comment]
ご返答ありがとうございます。
チャンネル変更時等、mirakurun.stdout.logへのlog出力は行われますが、
だいぶ軽減されました。

**Comment by kanreisa** [comment]
@epgdatacapbon 差し支えなければチャンネル変更時のログを見せていただけますか？（気になるところは伏字にしてOKです）

**Comment by epgdatacapbon** [comment]
こちらでお役に立ちますでしょうか。
必要であれば、一旦消去して最初から取り直しますのでご連絡ください。
状況としては、EPGStationでTBSの下町ロケットを録画し、録画終了後、TVTestにてBonDriver_Mirakurunで視聴を行ったログになります。
こうしてみると「loglevel: -2」で1番組を録画したのみにしてはログの出力が多いように思います。

- - GET /api/services HTTP/1.1 200 - - 0.962 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 156.881 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.372 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 2.172 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 136.512 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.388 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 2.232 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 166.485 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.382 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 2.042 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 115.040 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.367 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 2.105 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 99.579 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.356 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 0.881 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 164.123 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.406 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 3.812 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 140.917 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.210 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 1.413 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 153.609 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 2.013 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 1.019 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 189.550 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.376 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 0.962 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 137.193 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.206 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 3.238 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 100.997 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.419 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 3.143 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 137.952 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.359 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 3.225 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 163.439 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.311 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 1.245 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 111.947 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.396 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 1.719 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 148.173 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.351 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 2.275 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 157.884 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.218 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 0.870 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 96.941 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.413 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 0.896 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 81.488 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.385 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 2.718 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 129.454 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.406 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 2.015 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 124.874 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.360 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 1.903 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 139.342 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.350 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 1.886 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 145.158 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.195 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/services HTTP/1.1 200 - - 0.883 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs HTTP/1.1 200 - - 104.748 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/tuners HTTP/1.1 200 - - 0.213 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
- - GET /api/programs/327390104855120/stream?decode=1 HTTP/1.1 200 - - 17467.469 ms EPGStation/1.3.2 MirakurunClient/2.7.5 Node/v10.15.0 (linux)
192.168.1.xxx - GET /api/services HTTP/1.1 200 - - 2.158 ms -
192.168.1.xxx - GET /api/channels/GR/21/services/1056/stream?decode=1 HTTP/1.0 200 - - 909.522 ms -

**Comment by epgdatacapbon** [comment]
sudo npm install mirakurun@latest -g --unsafe --production
にてアップデートしたところ、視聴、録画ができなくなりました。
recpt1等が起動しないようです。
swagger-uiは動いており、そちらでもstreamの取得ができないようです。

**Comment by epgdatacapbon** [comment]
現在はlogがmaxLogHistoryで指定した行を超えると、日付を付されたファイル名で別に保存されるようですが、mirakurunを「loglevel: FATAL」以上で使い続けているとlogファイルが作り続けられるという仕様でしょうか。

**Comment by epgdatacapbon** [comment]
お忙しいところご返答ありがとうございます。
こちらのハードウェアの一時的な不具合のようで正常に視聴できました。

また、pm2-logrotateをインストールしていたため、logrotateの挙動を
mirakurunの自体の挙動と勘違いしておりました。

お手数おかけして申し訳ありません。
ありがとうございました。
