### ISSUE TITLE
【要望】BS/CSチャンネルスキャンの機能について

### ISSUE THREAD

**Issue by gifuhabu** [Chinachu/Mirakurun#43]
### Environment
* Version of Mirakurun: `2.8.3`
* Version of Node: `v10.15.0`
* Version of NPM: `6.6.0`
* Platform: Debian
* Architecture: x64

### Issue
お世話になっております。
有用なアプリケーションを作っていただきありがとうございます。
現状のチャンネルスキャン機能は地上波にしか対応していませんがBS/CSも対応する予定はありますでしょうか。
BS/CSはチャンネル名やチャンネル番号の変更が多いため、必要性を感じます。
channels.ymlの設定を手動で行うと間違いが起こりやすいので欲しいです。
以上お手数ですがよろしくお願いいたします。

**Comment by kanreisa** [comment]
こんにちは☺
考えてないこともないのですが、録画・チューニングコマンドに大きく依存する部分ですし、現状はプロジェクトの開発リソースが足りていないため、プロジェクトとして対応する予定はありません。そのため、いったん issue 自体は close したく存じますが、何か妙案や PR がありましたらお知らせいただけますと幸いです。

**Comment by ohmsa** [comment]
他所のサイトでスクリプトファイルで対処している例を見つけました。

https://www.jifu-labo.net/2019/02/mirakurn_channels_config/

録画→xml出力→データ抽出しているようですね。
