### ISSUE TITLE
【質問】channels.ymlの記述方法について

### ISSUE THREAD

**Issue by ohmsa** [Chinachu/Mirakurun#44]
### Environment
* Version of Mirakurun: `2.7.2`
* Version of Node: `v8.11.3`
* Version of NPM: `5.6.0`
* Platform: Windows 10
* Architecture: x64

### Issue
PX-Q3PE→Mirakurun→EPGStationという構成にて便利に使っております。
CSで一部の番組（ナショジオやカートゥーンネットワークなど）がEPGStationの番組表に出ていないことに気づきました。試しに<mirakurun IP adress>:40772/api/channelsをチェックしたところ、Mirakurun上でチャンネルとして認識されていないようです。

bondriver_Mirakurun→TVTestでチャンネルスキャンを行うとこれらのチャンネルは検出され、受信できております。channels.ymlの記述がおかしいのかと編集しようと思ったのですが、必要な情報（有効なサービスIDの調べ方）等がなかなかわかりません。

TVTestでチャンネルスキャンして得られたch2ファイルとchannels.ymlを比較して記述を改めようと思いましたが、写っているチャンネル同士でも値が違いうまくいきません。

channnels.ymlの記述方法についてどなたかヒントいただけないでしょうか。

**Comment by kanreisa** [comment]
こんにちは🌞

地上波以外のチャンネルスキャンは機能として実装されておらず、TVtestからもBonDriver_Mirakurun経由ではスキャンすることができません。
特に Windows 環境は公式にサポートするリソースがありませんので、Slack等で聞いてみてください。
どうぞよろしくお願いいたします。

**Comment by ohmsa** [comment]
返信ありがとうございます。

スキャン方法について伺っているのではなく、channels.ymlの記述について知りたかったのですが、

- name: CHANNEL-NAME-FOR-IDENTIFICATION # string
  type: CS # enum [GR|BS|CS|SKY]
  channel: '0' # string
  # below are optional
  serviceId: 1234 # integer
  space: 0 # integer: <space> as tuning space number in tuner command (default: 0)I
  isDisabled: false # Boolean

ここのchannelについてはch2ファイルのものと一致していますがserviceIdが違います。ServiceIdをch2のものと合わせれば良いかというと違うようで、「映っているチャンネルでも違う」ことがあり不可解です。

皆さん何らかの方法で情報を得て設定されていると思うのですが、その調べ方について伺いたく存じます。

**Comment by kanreisa** [comment]
TVtest で扱ってる ServiceID は16進数ではないですか？Mirakurunは10進数です。

(ここは情報交換の場ではありませんので、本当に心苦しいのですが、Slackなどほかの場を提供していますので、ご活用ください。
どうぞよろしくお願いいたします。)

**Comment by cuckoozero** [comment]
ohmsaさん、はじめまして。
自分も同じところでドツボってしまい、どうにかこうにかできるようになったためお役に立てるかもしれません。
よろしければkanreisaさんの指示に沿ってSlackの#questionにあげて頂けますか?

**Comment by kanreisa** [comment]
@cuckoozero
フォローいただきありがとうございます！🥺

**Comment by ohmsa** [comment]
すみません、サーバをリプレースしたらまた同じような問題（Mirakurun経由でCSが見えない／Bondriver直だとCSが見れる）が現れました。
当時のSlackの情報を見たいのですが、無くなったのでしょうか。
