### ISSUE TITLE
【要望】EPGデータ処理の無効化オプション

### ISSUE THREAD

**Issue by Ovis** [Chinachu/Mirakurun#49]
### Environment
* Version of Mirakurun: `2.8.3`
* Version of Node: `v10.15.1`
* Version of NPM: `6.4.1`
* Platform: Windows 10
* Architecture: x64

### Issue
本来Chinachuを利用することを前提に作られているわけですので、もし可能であれば・・・の要望です。

当方MirakurunからBonDriver_Mirakurunを経由して、EDCB(EpgDataCap_Bon)を利用して録画を行っております。
この構成ですと、Mirakurun側でEPGデータを取得していても、全く利用していない形になります。
先ほど要望として投稿させていただきました Issue https://github.com/Chinachu/Mirakurun/issues/48 
が発生した場合、チューナーがオープンできず、録画に失敗します。

つきましては、Mirakurun側でのEPGデータ取得を行わないオプションを実装いただけないでしょうか。

以上、よろしくお願いいたします。

**Comment by kanreisa** [comment]
@Ovis 実装しました。まだ需要がありましたら、試してみてください。

**Comment by Ovis** [comment]
ありがとうございます！
手元環境(Windows 10 x64)にて動作確認しました。問題ありません！
#48 の対応も含めご対応いただきましてありがとうございました。
