### ISSUE TITLE
[質問] バッファーあふれに関連する実装上の質問

### ISSUE THREAD

**Issue by masnagam** [Chinachu/Mirakurun#54]
### Environment
* Version of Mirakurun: `master`
* Version of Node: 質問なので省略
* Version of NPM: 質問なので省略
* Platform: 質問なので省略
* Status of Mirakurun: 質問なので省略

### Issue

はじめに，ソフトウェアを開発・公開してくださった方々に感謝致します．

利用している間にいくつか気になる現象を見つけ，それに関連する質問が３点あります．

確認の結果，不具合・改善点と判断された場合は，修正を試みようと思います．

#### TSFilter._writeでhighWaterMarkを超えるとcallbackを呼び出さない

[Writable._write](https://nodejs.org/dist/latest-v10.x/docs/api/stream.html#stream_writable_write_chunk_encoding_callback_1)の説明によると，callbackが呼び出されることを期待していますが，highWaterMarkを超えた場合，callbackを呼び出しません．

これは意図したことでしょうか？

関連性の確認は出来ていませんが，_overflowTimerのタイムアウトが発生すると，decodeのプロセスが残ったままになる現象を確認しています．

callbackを呼び出さないと，chunkはいつまでも処理中だと判断され，Node.jsはそれを開放することができません．恐らく，chunkを保持しているクロージャーも残り続けると思われます．この辺りが原因で，endやcloseのイベントが発生せず，decodeのプロセスが残り続けているのかもしれません．

あと，動いているようなので今のままでもいいのかもしれませんが，pushは[_read](https://nodejs.org/dist/latest-v10.x/docs/api/stream.html#stream_readable_read_size_1)で呼び出すことが期待されているように読めます．_writeではchunkをどこかに保存して，_readが呼び出されたらpushするのが正しいように思えます．

#### Program. findByNetworkIdAndReplaceが非同期処理になっていない

[async](https://github.com/Chinachu/Mirakurun/blob/master/src/Mirakurun/Program.ts#L167)がついていますが，処理の途中でイベントループに戻ることはありません．

これは実装漏れでしょうか？

BSチャンネルが登録されている場合，NetworkId#4がたくさんあるので，プログラム数が4000を超えることがあり，それなりの時間このメソッドから戻ってこなくなります．

Rock64で確認した限りだと，10秒以上かかることがあるみたいです．

#### Tuner. _getStreamでの~~async~~ await common.sleep(1000)の意図

前の質問に関連しますが，このコードの意図を教えてください．

Program. findByNetworkIdAndReplaceで長時間ブロックされるので，溜まったTSデータを読み書きすることを期待しているのかと推測しています．

ただ，私が手元でTSFilter.{_read|_write}にログを入れて確認した限りでは，チューナープロセスからのTSFilterへの書き込みは行われますが，TSFilterからdecodeプロセスなどへの書き込みは必ずしもこのスリープ中に行われるというものでもないように見えます．

**Comment by kanreisa** [comment]
こんばんは！

> **TSFilter._writeでhighWaterMarkを超えるとcallbackを呼び出さない**
> 関連性の確認は出来ていませんが

恐れ入りますが、現状問題を把握していませんので、ご確認いただけますでしょうか？
ちなみに、タイムアウトすると以下が実行されます。

1. https://github.com/Chinachu/Mirakurun/blob/6d68cb97489ff31dead769bdc339778ebb8fdbc0/src/Mirakurun/TSFilter.ts#L214
2. https://github.com/Chinachu/Mirakurun/blob/6d68cb97489ff31dead769bdc339778ebb8fdbc0/src/Mirakurun/TSFilter.ts#L754
3. https://github.com/Chinachu/Mirakurun/blob/6d68cb97489ff31dead769bdc339778ebb8fdbc0/src/Mirakurun/Tuner.ts#L422

また、`callback` を呼び出していない件の理由はよく覚えていませんので、
わざと overflow させてみて、正常に動くようでしたらマージできます。

> **Program. findByNetworkIdAndReplaceが非同期処理になっていない**

[この機能](https://github.com/Chinachu/Mirakurun/blob/master/doc/Mirakuruns.md)のためだけに[実装](https://github.com/Chinachu/Mirakurun/blame/6d68cb97489ff31dead769bdc339778ebb8fdbc0/src/Mirakurun/Program.ts#L167)され、[1箇所](https://github.com/Chinachu/Mirakurun/blob/6d68cb97489ff31dead769bdc339778ebb8fdbc0/src/Mirakurun/Tuner.ts#L346)からのみコールされているメソッドですので、重要度がさほど高くなく、実装漏れというか適当やった結果なんだと思います。 `async` 無意味になっていますね。今気づきました。

良い感じに非同期にしてくださるのであれば非常にありがたいです。

> **Tuner. _getStreamでのasync common.sleep(1000)の意図**

`await common.sleep(1000);` のことですね。

この `sleep(1000)` の意図は `TunerDevice#getRemotePrograms()` を連続で実行してしまうと、リモートの Mirakurun に一定の負荷がかかってしまうため、わざと間隔をあけているものです。長時間のブロックの件はそこまで遅い計算機を想定していなかったので特に考えていませんでした。

**Comment by masnagam** [comment]
おはようございます．
回答ありがとうございます．

> タイムアウトすると以下が実行されます

私もここで`close`が送られてdecodeプロセス（arib-b25-stream-testを使っています）が終了すると考えていたのですが，なぜか終了せず残り続けるという現象に遭遇しました．

同じ問題に遭遇する人が他にもいるかも知れませんので，以下に構成を記述しておきます．

* epgstation (rock64 machine1)
  * version: 1.4.8 (master HEADを使用)
* mirakurun-master + arib-b25-stream-test (rock64 machine2)
  * version: 2.10.1 (master HEADを使用)
* mirakurun-remote + tuner device (rock64 machine3)
  * version: 2.10.1 (master HEADを使用)
  * GR/BSのみ

os/node/mpnはすべて同じで以下の通りです．

* os: armbian stretch (4.4.174-rockchip64)
* nodejs: v10.15.3
* npm: 6.4.1

Dockerコンテナとして実行しています．

```Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:47:02 2019
 OS/Arch:           linux/arm64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:11:17 2019
  OS/Arch:          linux/arm64
  Experimental:     false
```

mirakurun-masterでバッファーがあふれたときに，arib-b25-stream-testが残り続けます．まだ解析前なので詳細不明ですが，[このelseブロック](https://github.com/Chinachu/Mirakurun/blob/master/src/Mirakurun/Tuner.ts#L413)で期待しているイベントが何らかの理由で発生しないものと推測されます．

> わざと overflow させてみて、正常に動くようでしたらマージできます。

了解しましました．試してみて意味ある修正であった場合は，PRを作成します．

> 良い感じに非同期にしてくださるのであれば非常にありがたいです。

配列のイテレーションを適当な長さで分割し非同期処理するようなライブラリなどがあった記憶がありますので，修正を検討してみます．

ブロッキングで実行していた処理を非同期にする場合，同時に動く可能性のある処理について確認が必要になりますので，わからないことが出てきたら，また質問させていただきます．

> リモートの Mirakurun に一定の負荷がかかってしまうため、わざと間隔をあけているものです

Rock64+Docker環境で計測したので載せておきます．

```console
$ curl -s http://mirakurun-remote:40772/api/programs?networkId=4 | jq .[].id | wc -l
    3980

$ curl -s http://mirakurun-remote:40772/api/programs?networkId=4 -o /dev/null -w '%{size_download}\n'
2406117  # 約2.4M

$ curl -s http://mirakurun-remote:40772/api/programs?networkId=4 -o /dev/null -w '%{time_starttransfer}\n'
0.596560  # 600ms程度．ばらつきがあるので，一番遅かった時間
```

ARIBを読んだことがないので間違った意見かもしれませんが，Network IDでプログラムを集めるのではなく，Service IDでプログラムを集めれば数が少なくなり，リクエストごとの負荷が下がる気がします．ただし，`save`の回数が増えるので，mirakurun-masterの応答性は下がるかもしれません．

```console
$ curl -s http://mirakurun-remote:40772/api/programs?serviceId=101 | jq .[].id | wc -l
     293
```

serviceIdはユニークみたいでした．

```console
$ curl -sSL http://mirakurun-remote:40772/api/channels | jq .[].services[].serviceId | wc -l
      46

$ curl -sSL http://mirakurun-remote:40772/api/channels | jq .[].services[].serviceId | uniq | wc -l
      46
```

**Comment by masnagam** [comment]
arib-b25-stream-testが残る問題は再現条件が判明した時点で別途PRを送ります．

現時点でわかっていることは

* `decoder.stdin`で`finish`イベントが起こらず，`decoder.kill("SIGKILL")`が呼び出されない
* Nodejsのドキュメントによると，`stdin`にデータが残っていると`end()`を呼び出しても`finish`が発生しない

ひとまず，こちらの質問は閉じます．
