### ISSUE TITLE
pm2によるPC起動時の実行において、他のPCからアクセスできない

### ISSUE THREAD

**Issue by epgdatacapbon** [Chinachu/Mirakurun#60]
### Environment
* Version of Mirakurun: `2.11.0`
* Version of Node: `v10.15.3`
* Version of NPM: `6.9.0`
* Platform: Linux Debian Stretch
* Status of Mirakurun: https://gist.github.com/... (from http://_mirakurun-server-ip_:40772/api/status)

### Issue
...
設定（.yml）ファイルを適切なフォルダに入れ
sudo npm install mirakurun -g --unsafe-perm --production
にてインストールを行った直後は、同じLANの他のPCからBonDriver_Mirakurunや
http://_mirakurun-server-ip_:40772/api/statusでアクセスできるが、
一旦再起動すると、他のPCからアクセスできなくなります。
なお、この状態でも「pm2 list」で正常に起動しているのが確認できますし、
実際に「ps aux」で「Mirakurun: Server」のプロセスも確認できます。

ここで「pm2 restart mirakurun-server」を行うと再びアクセスできるようになります。

なお、古いバージョン（2.9.0）では問題ありませんでした。

**Comment by kanreisa** [comment]
大変お手数ですが下記の対応をしていただけると助かります。

- https://gist.github.com/ に http://mirakurun-server-ip:40772/api/status の内容をコピペしてアップロード
- **再現させた状態で** 起動直後のログも ↑ にアップロード

```sh
# 再現させた状態で
sudo -i
pm2 -v
pm2 status

netstat -ap | grep Mirakurun
netstat -ap | grep 40772
```

**Comment by epgdatacapbon** [comment]
ご返答ありがとうございます。アップしました。
https://gist.github.com/epgdatacapbon/03fb296741c2bc00dd6bdfc6bca926cd
なお、この状態ではBonDriver_Mirakurunで初期化ができないエラーで視聴できませんが、
#pm2 restart mirakurun-server
で正常に動作するようになります。

**Comment by epgdatacapbon** [comment]
なお、2.10.1では問題ないようです。

これとは別にCSで1分くらい視聴すると止まってしまう症状が出ていて、
こちらも別に検証してみます。

**Comment by kanreisa** [comment]
ログを見る限り NIC に割り当てられている IP アドレスで LISTEN されていないようです。
2.11.0 で起動時間が短縮したことによる影響かもしれません。
NIC が有効になる前に起動してしまっている気がします。

一旦 PM2 のサービスを再登録してみてください
```
sudo -i
pm2 unstartup
sudo reboot # ここで一旦再起動して pm2 がスタートアップしないことを確認する
#
sudo -i
pm2 startup
```

適当に pm2 の起動を遅らせるか、NIC の初期化が遅延しないようにすると解決すると思います

**Comment by epgdatacapbon** [comment]
早速のご返答ありがとうございます。
一旦 PM2 のサービスを再登録しても解決しなかったため、
/etc/systemd/system/pm2-root.service
について
```
[Service]
ExecStartPre=/bin/sleep 5
```
を追加してpm2の起動を遅らせることにより対応できました。
ありがとうございました。

**Comment by akimasa** [comment]
横から失礼します。
下記のコマンドを実行するといかがでしょうか？
`sudo pm2 startup --wait-ip`

[PM2 2.9.0以降ではネットワークが起動するのを待ってから開始するオプション](https://github.com/Unitech/pm2/issues/3347)があるみたいです

**Comment by kanreisa** [comment]
すばら C

**Comment by epgdatacapbon** [comment]
pm2 Ver. 3.5.0で
```
sudo pm2 startup --wait-ip
```
と
```
sudo pm2 startup systemd --wait-ip
```
を試しましたが、うまくいきませんでした。

**Comment by yamaken-sapporo** [comment]
横からですが、 
> Platform: Linux Debian Stretch
とのことなので、systemdから pm2が動いてるかと思います。

/etc/systemd/system/pm2-root.service について

After=network.target
WantedBy=multi-user.target

になってますかね。
普通networkが立ち上がってからpm2が起動するはずですが、これでダメの場合、
systemd-networkd-wait-online
http://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

を有効にすれば解決できそうです。
sudo systemctl enable systemd-networkd (おそらくすでに有効のはず)
sudo systemctl enable systemd-networkd-wait-online
を実行し

/etc/systemd/system/pm2-root.service を

After=network-online.target
WantedBy=network-online.target

に書き換えればnetwork起動後にpm2を起動できるかと。

**Comment by epgdatacapbon** [comment]
現在の状態は下記のようになっています。
```
[Unit]
Description=PM2 process manager
Documentation=https://pm2.keymetrics.io/
After=network.target network-online.target
Wants=network-online.target
Restart=on-failure

[Service]
Type=forking
User=root
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/$
Environment=PM2_HOME=/root/.pm2
PIDFile=/root/.pm2/pm2.pid

ExecStartPre=/bin/sleep 5
ExecStart=/usr/lib/node_modules/pm2/bin/pm2 resurrect
ExecReload=/usr/lib/node_modules/pm2/bin/pm2 reload all
ExecStop=/usr/lib/node_modules/pm2/bin/pm2 kill

[Install]
WantedBy=multi-user.target network-online.target
```

**Comment by yamaken-sapporo** [comment]
>[Unit]
>Description=PM2 process manager
>Documentation=https://pm2.keymetrics.io/
>After=network.target network-online.target
>Wants=network-online.target
>Restart=on-failure

うーん、AfterとWantsで `network-online.target` が謎というか意味がないですね。
Wantsの方が不要かと思います。
ちなみにAfterとWantsの違いですがWantsは指定されているものが起動失敗しても
この場合においてだとpm2は起動してしまうので、切り分けができない気が。

ちなみにデフォルトテンプレートは下記のはずなのですが、色々変更しましたか？

https://github.com/Unitech/pm2/blob/master/lib/templates/init-scripts/systemd.tpl

**Comment by akimasa** [comment]
`sudo pm2 startup --wait-ip`を実行してもらっているので、下のテンプレートが使われていると思います。
https://github.com/Unitech/pm2/blob/master/lib/templates/init-scripts/systemd-online.tpl
AfterとWantsで`network-online.target`が指定されています。
PM2側の修正が必要でしょうかね？

**Comment by epgdatacapbon** [comment]
オリジナルだとうまくいかないのがことの発端なので
```
pm2 startup --wait-ip
```
を実行した結果、下記のテンプレートを使うようになっているようです。
https://github.com/Unitech/pm2/blob/master/lib/templates/init-scripts/systemd-online.tpl

やはりおかしいと思うので、今pull request書いてます。

**Comment by yamaken-sapporo** [comment]
> `sudo pm2 startup --wait-ip` を実行してもらっているので、下のテンプレートが使われていると思います。

あ、そいえばこの前提を忘れてました。
とりあえず、動いてよかった！
pm2にmargeされればみんな幸せ！

**Comment by akimasa** [comment]
AfterとWantsで`network-online.target`が指定されている例がほかにも多数見かけて、よくある間違いでもなさそうでした。
ので、調べてみました。

[systemdのドキュメント](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/)を思ったのですが、pm2へのPRはもしかすると不要だったかもしれません。
というのは、ネットワークが確実にオンラインになってからserviceを起動させるようにするには
1.  下記を.serviceに追加
```
After=network-online.target
Wants=network-online.target
```
2.  `systemctl is-enabled NetworkManager-wait-online.service systemd-networkd-wait-online.service`を実行して必要なサービスが有効になってることを確認（有効になっていなかったらどちらか適切な方を有効にする）

すればよいらしいです。

従って、下記のコマンドを実行する必要があります。
```
sudo pm2 startup --wait-ip
sudo systemctl enable systemd-networkd-wait-online
```
yamaken-sapporoさんのご指摘で2行目のコマンドが実行されて、うまくいくようになったということは無いでしょうか？
お手数ですがpm2の修正なしでも、うまくいくかどうか確認してみていただけますか？

**Comment by akimasa** [comment]
Debian Stretchを入れてみて気が付いたのですが、Debianはsystemd-networkdを使っていないみたいです。

なのでsystemd-networkd-wait-onlineの意味がなかったです…

```
After=network-online.target
WantedBy=network-online.target
```
Debian Stretchでpm2-root.serviceに上記の修正を加えてみましたが、LANが接続されていない状態で起動してしばらく経ってからLANに接続すると、MirakurunがLANのIPアドレスでLISTENしませんでした。
systemd-networkdを採用しているArch Linuxでは上記の修正なしで`sudo pm2 startup --wait-ip`を実行して、シャットダウン。LANが接続されていない状態で起動してしばらく経ってからLANに接続すると、LANに接続されるのを待ってからpm2が起動して、LANでLISTENしていました。

したがって、 Unitech/pm2#4285 の修正を行っても、うまくいかない場合がある気がします。修正なしでも環境によってはIPアドレス取得の遅延が起きても問題ない場合もあります。

Debian Stretchのネットワーク周りが怪しい気がします。ググったら、[Debianでnetwork-online.targetがうまく動いていないとの質問](https://unix.stackexchange.com/questions/209832/debian-systemd-network-online-target-not-working)がありました。自分が確認した限りではArchもRaspbianもIPアドレスが取得されるまでnetwork-online.targetに達することは無かったですが、DebianだけはIPアドレスが取得されていない状態ですぐにnetwork-online.targetに達してしまうようです。

Debianにsystemd-networkdが来れば簡単に解決できそうですが、それ以外に何かうまい方法はありませんかね？

**Comment by epgdatacapbon** [comment]
クリーンインストールして再度試してみました。
akimasaさんのおっしゃる通りパッチだけではダメで、下記のコマンドを実行する必要がありました。
```
sudo systemctl enable systemd-networkd
sudo systemctl enable systemd-networkd-wait-online
```

**Comment by akimasa** [comment]
返事が遅くなってすみません。

先ほど、こちらの環境でも試してみました。
クリーンインストールをした上で、epgdatacapbonさんの挙げてくれたコマンドを実行したところ、正常にアクセスすることができました！
PM2のパッチは無しで大丈夫でした。

Mirakurunのインストール後、下記のコマンドだけを実行すれば大丈夫そうです。
```
pm2 startup systemd --wait-ip
systemctl enable systemd-networkd
systemctl enable systemd-networkd-wait-online
```

**Comment by kanreisa** [comment]
`@2.12.0` で挙動を改善してみました。皆様フィードバックありがとうございました。
