### ISSUE TITLE
windows8.1でのインストールエラー

### ISSUE THREAD

**Issue by polo1kani** [Chinachu/Mirakurun#61]
### Environment
* Version of Mirakurun: `2.11.0`
* Version of Node: `v8.9.4`
* Version of NPM: `6.4.1`
* Platform: windows8.1 HOME
* Status of Mirakurun: https://gist.github.com/... (from http://_mirakurun-server-ip_:40772/api/status)

### Issue
windows8.1で、Mirakurunのインストールが出来ません。
osはすでに最新版にアップデートしております。
以前epgstationと一緒に構築しようとしていました。
powershellは管理者権限です。

なぜか以前インストールしたときは問題なく起動し、コンピューターの再起動をしても起動しました。
しかし、epgstationをコンピュータ起動時に起動する.batファイルを作ってスタートアップに登録してから、再起動すると、.batファイルが起動してからMirakurunが起動しませんでした。

それからいろいろ試しても解決せず、epgstationとMirakurun,nodejs,winser,batファイルを、すべて削除してからmirakurunを再インストールしようとしました。しかし以前できた方法でインストールできません。

windowsは非サポートなのは承知しておりますが、
対応いただければ幸いです。

以下ログです。

<details>
 <summary>使用した.bat</summary>
cd c:\epgstation

npm start
</details>

<details>
  <summary>powershellの内容</summary>

Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> npm install mirakurun@latest -g --production

> mirakurun@2.11.0 preinstall C:\Users\kazu\AppData\Roaming\npm\node_modules\mirakurun
> node bin/preinstall.js

C:\Users\kazu\AppData\Roaming\npm\mirakurun-epgdump -> C:\Users\kazu\AppData\Roaming\npm\node_modules\mirakurun\bin\epgd
ump.js
C:\Users\kazu\AppData\Roaming\npm\mirakurun -> C:\Users\kazu\AppData\Roaming\npm\node_modules\mirakurun\bin\cli.sh

> core-js@2.6.10 postinstall C:\Users\kazu\AppData\Roaming\npm\node_modules\mirakurun\node_modules\core-js
> node postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> mirakurun@2.11.0 postinstall C:\Users\kazu\AppData\Roaming\npm\node_modules\mirakurun
> node bin/postinstall.js && opencollective-postinstall

Version: node@v8.9.4 [OK]
Version: winser@v1.0.3 [OK]
No rights to manage services.
child_process.js:624
    throw err;
    ^

Error: Command failed: winser.cmd -i -a --startuptype auto --startcmd node.exe bin\init.win32.js --set AppPriority ABOVE
_NORMAL_PRIORITY_CLASS --set Type SERVICE_WIN32_OWN_PROCESS --set AppStdout C:\Users\kazu\AppData\Local\Mirakurun\stdout
 --set AppStderr C:\Users\kazu\AppData\Local\Mirakurun\stderr --env USERPROFILE=C:\Users\kazu --env LOCALAPPDATA=C:\User
s\kazu\AppData\Local --env USING_WINSER=1
    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at Object.<anonymous> (C:\Users\kazu\AppData\Roaming\npm\node_modules\mirakurun\bin\postinstall.js:154:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirakurun@2.11.0 postinstall: `node bin/postinstall.js && opencollective-postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirakurun@2.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kazu\AppData\Roaming\npm-cache\_logs\2019-10-30T12_03_47_954Z-debug.log

</details>
<details>

  
[2019-10-30T12_03_47_954Z-debug.log](https://github.com/Chinachu/Mirakurun/files/3788921/2019-10-30T12_03_47_954Z-debug.log)

**Comment by masnagam** [comment]
Issueを検索しただけで全く動作確認していませんが， #28 の問題に似ているように見えます．
解決法も書かれているようなので，まずは[これ](https://github.com/Chinachu/Mirakurun/issues/28#issuecomment-370322289)を試してみてはどうでしょうか？

**Comment by polo1kani** [comment]
#28はwinserの問題のようですが、こちらではwinserは正常に起動しているようです。インストールの時もそのコマンドを実行しましたが、winserは普通にインストールできております。
しかし、npm install mirakurun@latest -g --production　で失敗します。

管理者権限のPowershellの実行結果で Version: winser@v1.0.3 [OK] 以下で、No rights to manage services.（サービスを管理する権利がない）　と出ますが何の権限でしょうか?

**Comment by polo1kani** [comment]
丁寧な対応ありがとうございます。

指定の方法を行っても治りませんでした。
色々探した結果、環境変数のpathを疑い、環境変数のpathを再編集したところ解決しました。以前環境変数を触ったときに間違って削除したようです。windows10以前のwindowsでは、環境変数の一覧が横に改行なしで並ぶので、ミスに気付きにくいようです。

お騒がせしてすいませんでした。



windows系で似たようなエラーが出ている方のために、修正した環境変数の内容を貼っておきます。

nodejsのインストール先は、インストール時の標準にしてください。
書き替えるのはpathの値です。
環境変数を書き替えるときは　新規　ではなく、　編集　から行ってください。
環境変数の区切りは　;　です。


ユーザー環境変数
C:\Users\あなたのユーザー名\AppData\Local\microsoft\windowsapps;C:\Users\あなたのユーザー名\AppData\Roaming\npm

（あなたのユーザー名　へ、現在サインイン中のユーザー名を入れてください。）

システム環境変数
C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Windows\System32;C:\Windows;C:\Windows\System32\WindowsPowerShell\v1.0;


間違っていたり、存在しないない環境変数があれば、修正してください。
windows10では　;　が間になく、環境変数は箇条書きに並んでいます。

**Comment by polo1kani** [comment]
改行でわかりにくいので、修正内容を貼り付けます。
[修正　環境変数.txt](https://github.com/Chinachu/Mirakurun/files/3793393/default.txt)

**Comment by kanreisa** [comment]
よかったです！

**Comment by Remon-7L** [comment]
こちらクローズ済みですが私も `No rights to manage services.  ` で大変悩み、解決した為コメントさせて頂きます
結果から書きますとWindowsサービスの Server (LanmanServer) を無効化していた為net sessionが実行できずエラーとなっていました。
こちらを有効化したところ無事インストールできました。
エラー箇所のソースを読むのは大事ですね....。

**Comment by polo1kani** [comment]
メールから呼び出されてきました。
この件についてほとんど忘れていました。
そういえばこんな質問出しましたね。

とにかく解決してよかったです。
