### ISSUE TITLE
EITセクションのバージョンチェックの条件について

### ISSUE THREAD

**Issue by masnagam** [Chinachu/Mirakurun#62]
### Environment
* Version of Mirakurun: `2.13.0`

### Issue

以下，実際に動かして問題を見つけたわけではなく，コードのみを見て判断しています．なので，私の認識に誤りがある可能性もあります．

8538fd4aad78d5616bd6d1786df28ed37dd394e3 にてEITセクションのバージョン番号のチェックが行われるようになりましたが，この修正だと，以下の場合に問題があると思われます．

* バージョン番号が0に戻ったとき
  * バージョン番号は5ビットなので，15の次は0になります
  * この場合，`verDiff`は-15となり，L675の条件は`false`となります
* `verDiff === -1`の意味
  * EITセクションが短い期間に15回更新された場合，`verDiff`が-1になる場合があります（バージョン番号が一周して`verDiff = (N - 1) - N`となるような場合）
  * この場合のみ特別扱いするとは考えにくいので，恐らく条件式が間違っているものと推測されます

sub-tableを正しく処理するようにすると修正量が多くなりますし，また，sub-tableが実際にどのように運用されているかもはっきりしません（仮に仕様があったとしても，それに沿って運用されていないということもあり得る）．そこで，mirakc-aribでは[バージョン番号を無視する](https://github.com/masnagam/mirakc-arib/blob/master/src/eit_collector.hh#L223)ことにしました．これは[node-aribts](https://github.com/rndomhack/node-aribts/blob/master/lib/event_manager.js#L35)と同じ動作です．

mirakcでは，台風発生に伴いNHKの番組表が更新されたときも正しくEPGデータが更新できていたようだったので，バージョン番号を無視しても大きな影響はないと考えています．ただ，MirakurunとmirakcではEPGデータの更新方法に違いがありますし，実装方針はソフトウェアごとに異なります．ですので，最終判断はお任せします．

**Comment by kanreisa** [comment]
期待する動作は古いバージョンを無視することです。
バージョン番号が1つ加算した時と、0になったときは reset fields します。
これにより、いつまで経っても epgReady が発火しない問題が解決します。

しばらく動かしてみましたがそのようになっているようです。
いかがでしょうか。

**Comment by masnagam** [comment]
例えば以下のような状況が発生した場合，タイムアウトまでEITセクションを処理し続けてしまう可能性があります．

```
Section(00): version(13)  // ここでtargetFlag.version_numberが13になる
Section(08): version(13)
Section(10): version(11)  // verDiffが-2になり，reset fields
Section(18): version(11)
```

仕様上，バージョン番号は番組表が更新されるたびに１つづつ増えると思われます．EPG更新は１５分間隔なので，その間に複数回更新される可能性が考えられます．この場合，バージョン番号間の差は１より大きくなります．

あり得る場合をすべて考慮すると，`verDiff`は-15から15の間のあらゆる値を取る可能性があります．そのため，sub-tableを正しく処理しないような実装においては，バージョン番号を確認する意味がなくなります．

仕様上，EITセクションのバージョン番号はsub-tableの識別子の１つです．そのため，sub-table間のバージョン番号を比較することに意味はありません．なぜなら，バージョン番号はNID/TSID/SIDが同じsub-tableを区別するための識別子にすぎないからです（つまり，NID/TSID/SIDが同じsub-tableは１６個までしか作れないという意味）．

上記の帰結は，あくまでも私が仕様を読んで理解した内容に基づいています．私の理解が間違っている可能性は十分あります（専門家ではありませんので）．その場合には，誰か私の間違いを指摘してくれるこを希望します．

sub-tableの定義については，以下を参照してください．

* http://www.arib.or.jp/english/html/overview/doc/6-STD-B10v4_6-E2.pdf P60 (PDF全体でのページ番号は 72/321)

**Comment by kanreisa** [comment]
仰っていることは理解しています。
epg.ts で厳密な処理をしていない以上は epgReady を発火するのも目安程度なものです。今回のアップデートでは合理的な範囲内で修正されることを狙っています。

> EPG更新は１５分間隔なので，その間に複数回更新される可能性が考えられます．この場合，バージョン番号間の差は１より大きくなります．

15分間隔で EPGが更新される事は知りませんでした。教えていただきありがとうございます。

TSFilter 内で epgReady を発火するためのステートは次回に保持されない認識ですが、もし保持されるようでしたら確かに差は1より大きくなる可能性が高くなってきますね。

しばらく海外に居るためまともに修正できませんので、気になるようでしたら合理的な範囲内で修正いただけますと幸いです。(いずれにしても厳密な対応は不要です。)

**Comment by masnagam** [comment]
> 15分間隔で EPGが更新される事は知りませんでした。

MirakurunでのEPG更新が15分間隔という意味でした（設定で変わりますが）．放送局側での更新間隔については私も知りません．
https://github.com/Chinachu/Mirakurun/blob/master/src/Mirakurun/Channel.ts#L39

実装の意図は理解しましたので，特にこれ以上修正することはないと思います．クローズします．
