### ISSUE TITLE
Munin Pluginのshebang行でエラー

### ISSUE THREAD

**Issue by moja2** [Chinachu/Mirakurun#66]
### Environment
* Version of Mirakurun: `2.14.0`
* Version of Node: `v10.19.0`
* Version of NPM: `6.13.4`
* Platform: Ubuntu 18.04.4 LTS

### Issue
Munin Pluginを動作確認すると以下のエラーが発生します

```
$ sudo munin-run mirakurun_status
/usr/bin/env: 'node¥r': No such file or directory
```

https://github.com/Chinachu/Mirakurun/commit/d23fd6bba5e608fe6150229d87b84518fc72b923#diff-3fa19187042b21381f9577cd32dd7784 で改行コードがCR+LFに変更されたためと思います。mirakurun_status.js からCRを削除したら動きました。

**Comment by kanreisa** [comment]
@moja2 ご報告ありがとうございました。修正しましたのでご確認ください。

**Comment by moja2** [comment]
Mirakurun 2.15.2 で確認し、Munin上でMirakurunのグラフが更新されることを確認いたしました。
ありがとうございました。
