### ISSUE TITLE
Windows10 インストールエラー

### ISSUE THREAD

**Issue by Imanoob12** [Chinachu/Mirakurun#68]
### Environment
* Version of Mirakurun: `2.15.2`
* Version of Node: `v10.21.0` & `v12.18.0` & `v14.4.0`
* Version of NPM: `6.14.4`
* Platform: Windows 10 v1909
* Status of Mirakurun: N/A

### Issue
mirakurunを新規インストールで下記のエラーで落ちました。

node v10もv12もv14上でも試しても同じエラーです。Windowsもちゃんとアップデートしまったが変わりません。

どうすれば解決できるでしょうか？
よろしくお願いします～

```
> mirakurun@2.15.2 postinstall C:\Users\username\AppData\Roaming\npm\node_modules\mirakurun
> node bin/postinstall.js && opencollective-postinstall

Version: node@v14.4.0 [OK]
Version: winser@v1.0.3 [OK]
Use start command "node.exe bin\init.win32.js".
The program "mirakurun" was installed as a service.
  n v i r o n m e n t   s h o u l d   c o m p r i s e   s t r i n g s   o f   t h e   f o r m   K E Y = V A L U E .
 E r r o r   s e t t i n g   p a r a m e t e r   " A p p E n v i r o n m e n t E x t r a "   f o r   s e r v i c e   " m i r a k u r u n " !

Can't set environment for service
child_process.js:632
    throw err;
    ^

Error: Command failed: winser.cmd -i -a --startuptype auto --startcmd node.exe bin\init.win32.js --set AppPriority ABOVE_NORMAL_PRIORITY_CLASS --set Type SERVICE_WIN32_OWN_PROCESS --set AppStdout C:\Users\username\AppData\Local\Mirakurun\stdout --set AppStderr C:\Users\username\AppData\Local\Mirakurun\stderr --env USERPROFILE=C:\Users\username --env LOCALAPPDATA=C:\Users\username\AppData\Local --env USING_WINSER=1
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:15)
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\mirakurun\bin\postinstall.js:154:19)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1168,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirakurun@2.15.2 postinstall: `node bin/postinstall.js && opencollective-postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirakurun@2.15.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by kanreisa** [comment]
フィードバックありがとうございます。
Windows での動作については実験的な対応に留まっており、動作確認も行われておりません。
コミュニティにより1週間以上解決しない場合は issue をクローズしたいと思います。
また、1ヶ月以上経っても、最新の Windows で動作しないようであれば、サポートを完全に削除する予定です。

**Comment by 5ym** [comment]
node12のwindows環境で当方の環境では下記手順で構築できました
https://github.com/Chinachu/Mirakurun/blob/master/doc/Platforms.md#win32

**Comment by Imanoob12** [comment]
@5ym 
お返事ありがとうございます。

そうですね、多分私の環境に問題があると思います。問題なくそのインストールの仕方で問題できるようです。

再度インストールしてみたら別エラーが発生しました：

`> mirakurun@3.0.0 postinstall C:\Users\User\AppData\Roaming\npm\node_modules\mirakurun
> node bin/postinstall.js && opencollective-postinstall

Version: node@v12.18.0 [OK]
Version: winser@v1.0.3 [OK]
Use start command "node.exe bin\init.win32.js".
The program "mirakurun" was installed as a service.
Environment should comprise strings of the form KEY=VALUE.
Error setting parameter "AppEnvironmentExtra" for service "mirakurun"!

Can't set environment for service
child_process.js:651
    throw err;`

mirakurunのインストールは完成したが環境変数の設定に失敗したようかもしれません。

心当たりはありますでしょうか？

**Comment by 5ym** [comment]
@Imanoob12 
おそらくこの辺のエラーだと思いますが、powershellを管理者権限で実行されていますでしょうか
https://github.com/Chinachu/Mirakurun/blob/master/bin/postinstall.js#L122

**Comment by Imanoob12** [comment]
@5ym
はい、管理者権限で実行しました。このパソコンに英語版Windowsは入っていますが、ロカールが日本語ではないことが原因だと思われますか？
個人アカウントは日本語にしましたがそれは管理者環境に反映されないでしょうか。

**Comment by kanreisa** [comment]
念のため手順を確認したところ特に問題は無かったことを確認したのでこの Issue はクローズします。
誰かに助けてもらうためのレスは続けていただいて構いません。

**確認した環境**

- Mirakurun 3.1.0
- Windows 10 Pro for Workstations (English) v1909
- Node.js 12.18.1

```powershell
npm install winser -g
npm install mirakurun@latest -g --production
```
👇 
![image](https://user-images.githubusercontent.com/172910/85628731-97c2a480-b6ab-11ea-9782-c998f849b2cc.png)

**関連する Issue**

下記の Issue をみると、環境変数が壊れていたりしていて、環境変数の修正や、Windows のクリーンインストールで直ったようです。

- https://github.com/Chinachu/Mirakurun/issues/28
- https://github.com/Chinachu/Mirakurun/issues/61

**Comment by Imanoob12** [comment]
とっても不思議です。インストール手順は簡単なのに私の端末でなぜか落ちます。別端末でインストールしてみたら確かに問題なく成功しました。謎です。ありがとうございました。
