### ISSUE TITLE
Web UIが利用できない

### ISSUE THREAD

**Issue by 5ym** [Chinachu/Mirakurun#69]
### Environment
* Version of Mirakurun: `3.1.1`
* Version of Node: `v14.4.0`
* Version of NPM: `6.14.5`
* Platform: Linux Debian buster

### Issue
リリースいただいたので早速web UIの動作を確認しようとしたところ403が出て閲覧できませんでした。
環境としてはtraefikの下にmirakurunを置いているような感じです。
お手数おかけしますが確認のほどよろしくお願い致します。
![image](https://user-images.githubusercontent.com/13718335/85973013-7ac00580-ba0c-11ea-9bb9-309e19766270.png)

**Comment by 5ym** [comment]
直接開くと問題なく開きます。
![image](https://user-images.githubusercontent.com/13718335/85973070-9d521e80-ba0c-11ea-8d0a-77438274e536.png)

**Comment by kanreisa** [comment]
フィードバックありがとうございます。

直接 IP アドレスを入力してアクセスするか、localhost でアクセスしないと要求を拒否するようになっています。

これは [DNS Rebind Attack](https://en.wikipedia.org/wiki/DNS_rebinding) の防止が目的です。

また、Mirakurun は LAN 専用サーバーであるため、リバースプロキシによる動作は仕様としてサポート外です。
当該 DNS はグローバル IP が指定されています。これも仕様としてサポート外です。
それと同時に、この類は海外の違法ダウンロードユーザーが目をギラギラにして狙っていますので、速やかに上記画像の削除と DNS の再設定、可能であればグローバル IP の変更を推奨いたします。

どうぞよろしくお願いいたします。

参考: [Attacking Private Networks from the Internet with DNS Rebinding](https://medium.com/@brannondorsey/attacking-private-networks-from-the-internet-with-dns-rebinding-ea7098a2d325)

**Comment by 5ym** [comment]
@kanreisa 
ご指摘ありがとうございます。プライベートで利用する旨了解いたしました。
そこで要望なのですが、プライベートでも内向きでDNSを利用しておりそもそもlocalhostとプライベートIP以外でアクセスできるようにするこは不可能でしょうか。
検討のほどよろしくお願いいたします。

**Comment by kanreisa** [comment]
ありがとうございます。
フィードバックを受けまして、host 名を追加指定できる機能の追加を予定しています。
よろしくお願いいたします。
