### ISSUE TITLE
manページを作る

### ISSUE THREAD

**Issue by ghost** [Chinachu/Mirakurun#71]
### Issue
manページを作り、そこで設定ファイルの値について記述してはどうでしょうか。

**Comment by kanreisa** [comment]
ご投稿ありがとうございます。
当該機能については実装・メンテできる人的リソースが不足しているため、対応予定はありません。
もし、上記について我こそはと立候補いただけるのでしたら（他の方でも構いません！）、検討させていただきます。
どうぞよろしくお願いいたします。
