### ISSUE TITLE
録画コマンドの置き場所について

### ISSUE THREAD

**Issue by ghost** [Chinachu/Mirakurun#73]
Mirakurun 3.0.0ではdvbではない録画コマンドを使用する場合/usr/local/mirakurun/opt以下に置く必要があるようですが、これはFHS 3.0に違反しています。
/usr/local以下にプログラム固有のディレクトリを作ってはなりません( /直下にディレクトリを作ってそこにインストールするのが望ましくないのと同じです )。
/opt/mirakurunなどの適切なディレクトリに移動してはどうでしょうか。

出典: https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf (PDF注意)

**Comment by kanreisa** [comment]
a16ddc9b549c069e6af4087199e98b4961729946 で解消しました
