### ISSUE TITLE
LogLevel の変更が反映されない (docker)

### ISSUE THREAD

**Issue by tosono** [Chinachu/Mirakurun#78]
### Environment
* Version of Mirakurun: `3.3.0`
* Platform: Linux `Ubuntu Docker`
* Status of Mirakurun: https://gist.github.com/tosono/9323aa08feb04027c500f7d489f8274f

### Issue
WebのConfig -> LogLevelを変更し、Saveボタンを押しても画面上のLogLevelは`INFO(2)`に戻ってしまう。
`INFO(2)`以外どれに変えても、Saveをすると`INFO(2)`に戻る。

ただ、Server.ymlの設定値はちゃんと設定した値に変更されている。
![image](https://user-images.githubusercontent.com/2030831/89146575-266def80-d58f-11ea-87b0-139913580019.png)

**Comment by kanreisa** [comment]
ご報告ありがとうございます。
3.3.1 で修正しました。
