### ISSUE TITLE
Error: smsusb:smsusb_onresponse

### ISSUE THREAD

**Issue by mikewudev** [Chinachu/Mirakurun#80]
### Environment

- Mirakurun Docker, and local
- Ubuntu 20.04
- PX-Q1UD

### Issue

`/var/log/syslog` is filled with the following error.

```
smsusb:smsusb_onresponse: error, urb status -71, 0 bytes
```

Server is freezing randomly even after fresh install, wondering if this is the cause. Might not be directly related to Mirakurun, but even a 'Yes, this is expected' will be very helpful. Any ideas?

**Comment by kanreisa** [comment]
Thank you for first posting.

First, you have lacking many informations of your environment.

When reporting an issue we also need as much information about your environment that you can include. We never know what information will be pertinent when trying narrow down the issue.
(from contribution guidelines)

--

Unfortunately, We can't support on here about any tuner devices. please consider to ask on Discord community if needed.

p.s.
https://www.google.co.jp/search?q=smsusb:smsusb_onresponse
