### ISSUE TITLE
チャンネルスキャンが既存のエンドポイント/オプションで動作しなくなっている。

### ISSUE THREAD

**Issue by hiradimir** [Chinachu/Mirakurun#82]
### Environment
* Version of Mirakurun: `3.4.0`
* Version of Node: `v14.15.3`
* Version of NPM: `6.14.9`
* Platform: 
  * Linux raspberrypi 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux
* Status of Mirakurun: 
  * https://gist.github.com/hiradimir/d7f3eaa5bac3b8a7086240cf1f824a5e

### Issue

チャンネルスキャンが既存のエンドポイント/オプションで動作しなくなっていました。
```
$ sudo curl -X PUT "http://localhost:40772/api/config/channels/scan"
channel scanning... (type: "GR")

-> total 0 channels (of Takeover is 0) found and 46 channels stored.

channel scan has completed and saved successfully.
**RESTART REQUIRED** to apply changes.
```

#79 の PR が契機と思われます。

挙動としてはminCh/maxChを指定すると動作するため、

<details>

```
$ sudo curl -X PUT "http://localhost:40772/api/config/channels/scan?type=GR"
channel scanning... (type: "GR")

-> total 0 channels (of Takeover is 0) found and 46 channels stored.

channel scan has completed and saved successfully.
**RESTART REQUIRED** to apply changes.
$ sudo curl -X PUT "http://localhost:40772/api/config/channels/scan?type=GR&minCh=13&maxCh=67"
channel scanning... (type: "GR")

channel: "13" ...
-> 3 services found.
-> {"name":"ＮＨＫＥテレ","type":"GR","channel":"13"}

channel: "14" ...
```

</details>

以下で判定が想定通りで無いように見えました。
https://github.com/Chinachu/Mirakurun/blob/a8674a1e1011d6062d287a581479f40339f6f306/src/Mirakurun/api/config/channels/scan.ts#L66-L68

----

以下は推測です。

API定義上のデフォルト値も消えている。
https://github.com/Chinachu/Mirakurun/blob/a8674a1e1011d6062d287a581479f40339f6f306/src/Mirakurun/api/config/channels/scan.ts#L304-L315

fw? middleware? に何を使っているのか把握出来ていないのですが、
GRとかのデフォルト値が扱われているところをみると、
type: "integer" で、 `0` に丸められる挙動になってしまっているのでは無いでしょうか。

**Comment by kanreisa** [comment]
ご報告ありがとうございます。バグです。
`@3.4.1` で[修正](c7466ff7641a4ea9a37d251234e9be21fdb205e4)したのでご確認いただけますでしょうか？

**Comment by hiradimir** [comment]
@kanreisa 
対応ありがとうございます。
`@3.4.1` にて解消されていることが確認できました。
