### ISSUE TITLE
rootでなくユーザーで動かしたい

### ISSUE THREAD

**Issue by Tomon613** [Chinachu/Mirakurun#83]
```
 [hoge@localhost ~]$ mirakurun init
Error: root please.
[hoge@localhost ~]$ 
```

mirakurunをrootでなくユーザーで動かしたいのですが、できないでしょうか？
mirakurunがrootを要求している理由はどういったものでしょうか？

mirakurunをrootで動かしたくない理由ですが、ユーザーでnodejsの管理を行なっているからです。ユーザーのanyenv(nodenv)でnodejsを管理しており、その管理下にnpmおよびmirakurunを導入したため、rootからはフルパスを指定しないと操作できません(導入にsudoは使用しないのではなくできません)。

```
[root@localhost ~]# mirakurun restart  
bash: mirakurun: コマンドが見つかりません
[root@localhost  ~]# /home/VTomonC/.anyenv/envs/nodenv/shims/mirakurun restart
Use --update-env to update environment variables
...

[root@localhost ~]# 
```

**Comment by kanreisa** [comment]
初投稿ありがとうございます。

issue を投稿する際はできる限りご自分の環境情報を記載してください。
我々は皆さんの環境について何一つ知りません。
全ての issue に対して対話方式で探っていくのは非常に大変なことです。
ご協力をお願いいたします。

When reporting an issue we also need as much information about your environment that you can include. We never know what information will be pertinent when trying narrow down the issue.
(from contribution guidelines)

--

> mirakurunをrootでなくユーザーで動かしたいのですが、できないでしょうか？

Docker を利用する (推奨) か、下記のようなコマンドでユーザーで動かせます。
npm 経由でインストールしても直接ディレクトリで npm start すれば動きます。
設定ファイル等は[こちらの環境変数](https://github.com/Chinachu/Mirakurun/blob/master/docker/container-init.sh#L3-L7)で変更できます。

```sh
git clone git@github.com:Chinachu/Mirakurun.git
cd Mirakurun
npm install
npm run build
npm run start
# pm2 を使う場合
pm2 start processes.json
# 以降 pm2 コマンドで直接管理できる
```

> mirakurunがrootを要求している理由はどういったものでしょうか？

現在は主に下記の通りです

- [renice と ionice](https://github.com/Chinachu/Mirakurun/blob/5b41b78ee5feb630754ef459204d8ed633928a7c/src/server.ts#L22-L23) をしないとTSの配信でプチフリが発生するため
  - ご自分で renice と ionice を実行するか、リアルタイム視聴をしないのであれば大抵問題ありません
- mirakurun コマンドは root で動いている pm2 のみを操作する
  - ユーザーでも root でも実行できるようにしてしまうと、pm2 プロセスがユーザーごとに多重に起動してしまいます

ご質問があれば Discord でお願いいたします。
どうぞよろしくお願いいたします。
