### ISSUE TITLE
Mirakurunが再起動を繰り返す

### ISSUE THREAD

**Issue by Marron0421** [Chinachu/Mirakurun#84]
### Environment
* Version of Mirakurun: `2.5.0`
* Version of Node: `v 4.15.4 `
* Version of NPM: `不明`
* Platform: Docker

### Issue

Dockerにて構築しましたが、エラーによって再起動を繰り返してしまいます。
一度イメージをすべて削除した上で再度ビルドしましたが症状は改善しませんでした。
```
starting pcscd...
Using reader plug'n play mechanism
Scanning present readers...
Waiting for the first reader...   
 - 
> mirakurun@3.5.0 start /app
> node -r source-map-support/register --max_old_space_size=512 lib/server.js
renice: failed to set priority for 41 (process ID): Permission denied
Error: Command failed: renice -n -10 -p 41
renice: failed to set priority for 41 (process ID): Permission denied
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.<anonymous> (/app/src/server.ts:22:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirakurun@3.5.0 start: `node -r source-map-support/register --max_old_space_size=512 lib/server.js`
npm ERR! Exit status 1
npm ERR! Failed at the mirakurun@3.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-29T18_39_11_508Z-debug.log
stopping pcscd...
```
...

**Comment by stu2005** [comment]
ド素人でも良ければお力にならせてください、、、
ビルドと仰っていますが、それはDockerfileからイメージを構築したかそれともDockerHubの公式イメージを使用したかのどちらかだと思うのですが、どちらでしょうか、(コンテナ内でPermission deniedが吐かれてるのが不可解)

**Comment by stu2005** [comment]
多分コンテナ内で
https://askubuntu.com/questions/779657/how-to-change-the-priority-of-the-process-using-command-line
と同じことが起きてる気がします

**Comment by kanreisa** [comment]
issue を投稿する際はできる限りご自分の環境情報を記載してください。
我々は皆さんの環境について何一つ知りません。
全ての issue に対して対話方式で探っていくのは非常に大変なことです。
ご協力をお願いいたします。

--

> Version of Mirakurun: 2.5.0
> Version of Node: v 4.15.4
> Version of NPM: 不明
> Platform: Docker

- 環境情報が全て間違っています。何一つ、正しくありません。
- ログだけではなく、実行したコマンドも必要です。Docker で構築したのであれば、Docker をインストールして設定するコマンドから貼ってください。
- 他人が再現できるように必要な情報を提供してください。

情報を再度整理していただき、バグの可能性があれば Reopen してください。その他の場合は Discord で質問してください。
github で質問に対応するリソースが不足しているため、ご理解のほど、どうぞよろしくお願いいたします。
