### ISSUE TITLE
Mirakurun:getServices()で暴走する

### ISSUE THREAD

**Issue by nison-okrock** [Chinachu/Mirakurun#86]
### Environment
* Version of Mirakurun: `3.5.0`
* Version of Node: `v14.15.4`
* Version of NPM: `6.14.10`
* Platform: CentOS Linux release 7.8.2003 (Core)
* Status of Mirakurun: https://gist.github.com/nison-okrock/b31b8889920b1fe6db2040df3c4453bd

### Issue
多段接続にて、Mirakurun 3.5.0環境(下記 192.168.xxx.xxx)に接続した際に、無限ループが発生します。
最初のMirakurun:getServices(): 

> 0|mirakurun-server  | 2021-02-08T07:39:21.137+09:00 info: ChannelItem#'BS:BS03_0' serviceId=191 check has started
> 0|mirakurun-server  | 2021-02-08T07:39:21.138+09:00 info: TSFilter has created (serviceId=null, eventId=null)
> 0|mirakurun-server  | 2021-02-08T07:39:21.138+09:00 info: TSFilter is waiting for serviceId=null, eventId=null
> 0|mirakurun-server  | 2021-02-08T07:39:21.138+09:00 debug: TunerDevice#6 start stream for user `Mirakurun:getServices()` (priority=-1)...
> 0|mirakurun-server  | 2021-02-08T07:39:21.138+09:00 debug: TunerDevice#6 kill...
> 0|mirakurun-server  | 2021-02-08T07:39:21.138+09:00 debug: TunerDevice#6 > remote: exit.
> 0|mirakurun-server  | 2021-02-08T07:39:21.140+09:00 info: TunerDevice#6 process has closed with exit code=0 by signal `null` (pid=6253)
> 0|mirakurun-server  | 2021-02-08T07:39:21.240+09:00 info: TunerDevice#6 released
> 0|mirakurun-server  | 2021-02-08T07:39:21.240+09:00 debug: TunerDevice#6 spawn...
> 0|mirakurun-server  | 2021-02-08T07:39:21.246+09:00 info: TunerDevice#6 process has spawned by command `node lib/remote 192.168.xxx.xxx 40772 BS BS03_0 decode` (pid=6260)
> 0|mirakurun-server  | 2021-02-08T07:39:21.246+09:00 info: TunerDevice#6 streaming to user `Mirakurun:getServices()` (priority=-1)
> 0|mirakurun-server  | 2021-02-08T07:39:21.302+09:00 debug: TunerDevice#6 > remote: {
> 0|mirakurun-server  |   host: '192.168.xxx.xxx',
> 0|mirakurun-server  |   port: 40772,
> 0|mirakurun-server  |   type: 'BS',
> 0|mirakurun-server  |   channel: 'BS03_0',
> 0|mirakurun-server  |   decode: true
> 0|mirakurun-server  | }

発生するループ: 

> 0|mirakurun-server  | 2021-02-08T07:39:21.471+09:00 debug: TunerDevice#6 > remote: (error) undefined undefined
> 0|mirakurun-server  | 2021-02-08T07:39:21.471+09:00 debug: TunerDevice#6 > remote: exit.
> 0|mirakurun-server  | 2021-02-08T07:39:21.472+09:00 info: TunerDevice#6 process has closed with exit code=1 by signal `null` (pid=6260)
> 0|mirakurun-server  | 2021-02-08T07:39:21.573+09:00 info: TunerDevice#6 released
> 0|mirakurun-server  | 2021-02-08T07:39:21.573+09:00 debug: TunerDevice#6 spawn...
> 0|mirakurun-server  | 2021-02-08T07:39:21.573+09:00 warn: TunerDevice#6 respawning because request has not closed
> 0|mirakurun-server  | 2021-02-08T07:39:21.578+09:00 info: TunerDevice#6 process has spawned by command `node lib/remote 192.168.xxx.xxx 40772 BS BS03_0 decode` (pid=6267)
> 0|mirakurun-server  | 2021-02-08T07:39:21.633+09:00 debug: TunerDevice#6 > remote: {
> 0|mirakurun-server  |   host: '192.168.xxx.xxx',
> 0|mirakurun-server  |   port: 40772,
> 0|mirakurun-server  |   type: 'BS',
> 0|mirakurun-server  |   channel: 'BS03_0',
> 0|mirakurun-server  |   decode: true
> 0|mirakurun-server  | }
> 0|mirakurun-server  | 2021-02-08T07:39:21.636+09:00 debug: saving services...

### ためしたこと
- channelsでBS03_0を無効にしましたが、依然としてBS03_0でエラーが発生します。
- 同mirakurunに対し、TvTest(Bondriver_Mirakurun.dll)にて直接接続した際は、問題なく視聴できています。

**Comment by kanreisa** [comment]
issue を投稿する際はできる限りご自分の環境情報を記載してください。
我々は皆さんの環境について何一つ知りません。
全ての issue に対して対話方式で探っていくのは非常に大変なことです。
ご協力をお願いいたします。

--

- GS, BS 共に再現しませんでした。
- 多段接続しているのであればその全ての環境情報、プライベートIPアドレス、設定ファイルとログを gist 等にアップロードしてください。
- 他人が再現できるように必要な情報を提供してください。

情報を再度整理して Reopen をお願いします。
