### ISSUE TITLE
複数チャンネルで同一TSIDを共有するチャンネル録画において映像音声破綻が起こる

### ISSUE THREAD

**Issue by sandhill2000** [Chinachu/Mirakurun#92]
### Environment
* Version of Mirakurun: `3.5.0`
* Version of Node: `14.15.4`
* Version of NPM: `6.14.11`
* Platform: Ubuntu Server 20.04.2 LTS
* 番組録画環境: EPGStation 2.1.8

### Issue
表題の件、特定の条件で録画データの破損が起こる件についてEPGStationの方で問合せの
Issueを出したところ、EPGStationではMirakurunのストリーム出力をそのまま使用している
とのことなのでこちらに問合せさせていただきます。

発生条件：
・複数チャンネルで同一TSIDを共有しているチャンネルの録画中に起こる。
　※スターチャンネル2&3で確認
・チャンネルAで5.1ch放送中に並行でチャンネルBでモノorステレオ放送を録画していて
　チャンネルAの番組本編が終わり、番宣等のステレオ放送に切替わる瞬間に
　チャンネルBの録画の数十～数百におよぶTSパケットのペイロード破損が発生、その後
　回復する。
　※現象が発生する音声切替わりパターンは他にもあるかもしれない

この現象で破損するTSパケットは、TSヘッダが全く正常なままTSペイロードだけが
そっくり別物になるという事象。TSヘッダが正常なのでTSパケットの体裁として正常と
見做されるようで、破損部分においてドロップログにはdropもerrorも現れない。
破綻を確認するには録画ファイルをTMPG SmartRenderer6を使用して再エンコード
箇所チェックをかけて、現れるはずのない所に現れた再エンコード箇所を編集画面で
確認すると破綻箇所が目視でき、同じ箇所をVLCやPS3で目視しても破綻が確認できる。

同時間の同番組をWindows+EDCBで録画したものではこうした現象は起こらない。
Mirakurun+EPGStationとEDCBで同時に録画したTSからMurdocCutterでM2Vパケットだけを
取り出して比較した結果、Mirakurun+EPGStation側で破損したデータ部分において
・TSヘッダは両者で完全一致(つまりTSヘッダは正常)
・TSペイロードが全く別物
ということが判明。

複数チャンネルで同一TSIDを共有するチャンネルは他にBSの民放キー局チャネル等が
あるものの(BS朝日1/2/3など)、スターチャンネル2/3のように普段から全然違う番組を放送
したり、かつ5.1chとモノ/ステレオ放送が両チャンネル個別に頻繁に変わることがないので
気付く人が少ないだろうと思われます。
恐らくMirakurunのTSフィルタ処理に、今回の条件下で起こる問題が内在しているのではと
思います。
自分はスターチャンネル3の海外ドラマ一括放送を録画していてフレーム破綻に困り
対策のためスターチャンネル2/3に限ってEBCDでも録画するようにしましたが、
両方のTSが得られたこともあって折角なので今回の比較をしてみました。

環境的になかなか再現・解決が難しいケースかもしれませんが、対処の上で必要な情報が
ありましたら提供しますのでよろしくお願いします。
...

**Comment by kanreisa** [comment]
こんにちは、ご報告ありがとうございます。

以下のデータを gist にまとめてアップロードして共有いただけますでしょうか？
一部情報はプライバシーの事情もあるかと思いますので、
gist を Private 設定にして私の github プロフィールに記載されている
メールアドレス宛に共有いただいてもかまいません。

- `/api/config/tuners`
- `/api/config/channels`
- `/api/services`
- (事象の再現を問わず) 当該チャンネル2/3を同時に録画している状態の時の `/api/tuners` と `/api/status`
- LogLevel を DEBUG (3) にしてある状態で、事象が再現した時間前後を含むログ

現在多忙につき、すぐには調査できないので、引き続き事象の切り分け等を行っていただき、
分かったことがあればご共有いただければスムーズに対処できるかと思います。
また、当該のチャンネルはこちらでは契約しておらず、検証困難のため、ご協力が必要です。
Discord 上での ID を教えていただければ、必要に応じて連絡させていただきます。
どうぞよろしくお願いいたします。

**Comment by sandhill2000** [comment]
こんばんは、お返事ありがとうございます。
情報提供の件承知しました。
平日は時間がとりにくいので少しご提供が遅くなるかと思いますがよろしくお願いいたします。

**Comment by sandhill2000** [comment]
こんばんは。
先ほど情報をメールでお送りしましたが、少々バイナリも含めた関係でデータ類はメール添付にしました。ご確認ください。
よろしくお願いいたします。

**Comment by sandhill2000** [comment]
本件、kanreisa様とやりとりしつつ検証を進めた結果、究明できました。
recpt1のコマンドラインから--b25オプションを除去し、デコーダにarib-b25-stream-testを使うことで回避できました。つまり原因はrecpt1のb25デコード機能にありました。

スタチャン2/3等のマルチCHストリームに対してrecpt1の--b25オプションによるストリーム復号化を実行している際、片方のチャンネルで番組切替わりによる音声のモノ/ステレオ/5.1chの変更(＝音声PID移行)が起こった瞬間に他方のチャンネルで映像/音声TSのTSペイロードが化けるようです。化けるというかそこだけmulti8暗号解除が漏れるのかも。
kanreisa様ありがとうございました。
