### ISSUE TITLE
Bash補完の対応

### ISSUE THREAD

**Issue by hamach-boop** [Chinachu/Mirakurun#96]
Bashで、mirakurunコマンドのサブコマンドやオプションをタブ補完できるようにしてはどうでしょうか。

**Comment by kanreisa** [comment]
ご投稿ありがとうございます。
当該機能については実装・メンテできる人的リソースが不足しているため、対応予定はありません。
もし、上記について我こそはと立候補いただけるのでしたら（他の方でも構いません！）、検討させていただきます。
どうぞよろしくお願いいたします。
